[#to-children, short="To the Youth of the Society of Friends"]
== A Letter to the Children and Youth of the Society of Friends

by Frederick Smith

Dear Young Friends,

I regard as some of the most pleasing circumstances of my life,
the opportunities I have had of contemplating the innocence and simplicity of such youth,
as have had their minds regulated and governed by divine love,
and feared to do evil lest they should offend that Almighty Being,
under whose precious influence they have desired to be preserved.
Under this consideration, I feel myself engaged to offer to you a few hints,
which I trust will not be unprofitable.

In the first place, I wish to call your attention to a subject,
with which there is little doubt but most of you are acquainted; namely,
the proneness there is in your nature to do evil--to yield
to the secret temptations that frequently oppress you,
and urge you, perhaps to commit sins, which you would be ashamed to acknowledge,
even to your most intimate companions.
This, I apprehend, few of you will deny.
At the same time, some of you must also acknowledge, that,
notwithstanding you have been thus tried,
as you have considered the dreadful consequences of yielding to these temptations,
you have been sometimes enabled to resist them;
and this has afforded you solid peace and satisfaction.

Thus then,
it is evident that you feel within yourselves a principle
of good and a principle of evil;
that when evil presents itself in any form, you know it to be such; and when thus known,
a fear and dread usually accompanies it.
This is the effect of the grace of God, or the divine light of Christ within you.
And as this grace or light is attended to, it will always be you preserver;
according to the declaration of the Apostle Paul,
"`The grace of God that bringeth salvation, hath appeared unto all men; teaching us,
that denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly in this present world.`"--Tit. 2:11. Here then,
we see the goodness of the Almighty: when any sin,
which would have been gratifying and pleasing to you has presented itself,
it has been pointed out to you to be sinful; you have believed it to be so,
and thus have been warned against falling into the snare of the enemy.
Your own experience also has already taught you,
that though in many instances you have been preserved,
it has not been without great difficulty; and that,
had you given way to your own inclinations,
you would have fallen into many grievous sins.
But it was your Lord and Saviour who so tenderly watched over you;
and it is through his lovingkindness that you have been so often preserved.
Temptation you will perceive is gradual: at first evil thoughts present themselves,
then evil desires; and if the divine Instructor be not attended to,
these desires produce evil actions; which, being offensive in the divine sight,
occasion those painful sensations which the commission of sin leaves on the mind.
And it is a great favour that sin does leave a sting behind,
because this leads to repentance.
For though the Lord has all power in his hands, and sees all the evil of your hearts,
knows every thought, and is acquainted with every sin you commit,
and could punish those who act contrary to his holy will made known in the heart;
yet his love is such, that if those who have transgressed, truly and sincerely repent,
and use all their endeavours to avoid sinning any more, he will forgive them, and will,
for his Son`'s sake, again take them into his favour.
How good then ought you to be, when you see he deals so kindly and tenderly with you!
What an abundant favour it is, that he offers you, and will give you,
the ability to do his will, and thereby to please him The more, therefore,
you attend to his instructions to avoid the evil and to choose the good,
the more you will experience true happiness and peace.
Looking at these things, I have much desired that you, my dear young friends,
would ponder them in your hearts,
and so conduct yourselves as to draw down his favour and love;
for as that is the greatest blessing you can enjoy,
so I am persuaded you cannot do too much to obtain it.

I shall now further endeavour to shew you, how you may, by divine assistance,
overcome those evil propensities of which I have been speaking.
It is very certain, that there is a secret principle in our minds, as I have before said,
which points out to us what is evil, and teaches us to avoid it.
It is to this Teacher, I would recommend you to be particularly attentive; because,
if it be slighted, though it may for a time discover to you what is wrong,
yet by continual disobedience, you will find, that,
instead of your growing in grace and in goodness, you will slide into hardness of heart,
and sooner or later bring yourselves into great misery and distress.
For what greater distress can we be brought into, than to see and feel, that,
having acted contrary to the divine will, we have displeased our Heavenly Father;
and that our continued evil conduct has left us but
little hope of gaining his favour any more.
Use all your endeavours then, to avoid getting into this deplorable state.
Let the pious resolution of David be yours:
"`I will take heed to my ways that I sin not:`"-- Ps. 39:1, so you will find,
that peace and comfort will abound in your hearts.

The great means of gaining strength to do the will of your Father who is in heaven,
is to look to him for help; for he alone can give efficacy to your exertions.
Always live as though you were sensible you were immediately in his sight;
and strive to pray to him to preserve you;
and consider him as a tender parent who loves his children,
who is ever ready to do them good,
and whose will is that they should be sensible of his presence, power, and love.
These dispositions towards your Almighty Protector,
will increase your desire to follow him wherever he may choose to lead you;
they will so clothe your minds with divine love,
that you will be willing to forsake everything which
may be likely to obstruct the enjoyment of it,
or in other words, to obstruct your union with God.
You will, on this account, endeavour to avoid thinking of evil,
either as to the giving way to temptation, or indulging any disposition to lying, deceit,
envy or ill nature towards any one; you will also know that wanton cruelty,
even to the most helpless animals,
(which are creatures of God`'s making as well as yourselves,) passion, resentment,
hatred and revenge, are dispositions which proceed from your own evil or fallen nature,
and will tend to separate you from the Giver of all good.
It is a certain truth that "`God is love; and he that dwelleth in love, dwelleth in God,
and God in him.`"
--1 John 4:8. The youth whose mind is in this state,
and who is desirous of contemplating the goodness of the Almighty,
will feel a sense of gratitude,
that he has a capacity given him of attaining to that most exalted of all enjoyments,
a union with his Maker.
It is therefore our own fault, seeing we are mercifully favoured with the means,
if we do not avail ourselves of so great a blessing.

The evil to which I have before adverted,
is declared in Scripture to have arisen from the fall of man.
The first man, Adam, was created in a state of innocence, free from sin.
His nature was not corrupt, until, by disobeying the divine command, he transgressed.
In consequence of this he was driven out of Paradise,
a place of the highest earthly happiness;
and instead of continuing to enjoy this state of perfection and innocence,
he became subject to the evil propensities we also feel;
though none are condemnable till they have yielded to temptation.
But although Adam by thus transgressing, introduced sin and death into the world,
and rendered himself an object of divine displeasure;
yet the Almighty had compassion on mankind, and appointed a way for their salvation,
through his Son Jesus Christ; who in due time took upon him our nature,
and suffered and died for the sins of the world,
as is at large set forth in many parts of the Scriptures.

The Sacred Writings further shew us,
that if we are willing to be under the guidance of Jesus Christ,
we shall be restored to that blessed state from which Adam fell;
as says the apostle Paul, "`As in Adam all die,
even so in Christ shall all be made alive.`"-- 1 Cor.
15:22. Also "`The first man Adam was made a living soul,
the last Adam (by which Christ is meant) was made
a quickening (or life-giving) spirit.`"--ver. 45.

I shall now quote a few other Scripture testimonies, from the Old and New Testament,
concerning Jesus Christ;
which will shew you the connection there is in the Sacred Writings,
and also the advantage there is in comparing them together.

Isaiah, speaking prophetically of the coming of Christ, says,
"`For unto us a child is born, unto us a son is given;
and the government shall be upon his shoulder: and his name shall be called Wonderful,
Counsellor, The Mighty God, The Everlasting Father, The Prince of Peace.
Of the increase of his government and peace there
shall be no end.`"--Isa. 9:6. The same prophet,
speaking of his death and sufferings,
and of the blessings that would arise from them to mankind,
as a sacrifice for sinners and as a pattern of patience and humility, says,
"`Surely he hath borne our griefs, and carried our sorrows;
he was wounded for our transgressions; the chastisement of our peace was upon him,
and with his stripes we are healed.
All we like sheep have gone astray; we have turned every one to his own way;
and the Lord hath laid on him the iniquity of us all.
He was oppressed, and he was afflicted, yet he opened not his mouth;
he was brought as a lamb to the slaughter, and as a sheep before his shearers is dumb,
so he opened not his mouth.`"
Read the whole of the fifty-third chapter of Isaiah.

The following show the completion of the foregoing declarations;
and that salvation and redemption come through Jesus Christ.

"`For unto you is born this day, in the city of David, a Saviour,
which is Christ the Lord.`"--Luke 2:11.

"`For God so loved the world, that he gave his only begotten Son,
that whosoever believeth in him should not perish,
but have everlasting life.`"--John 3:16.

"`I am the door.
By me if any man enter in, he shall be saved, and shall go in and out,
and find pasture.`"--John 10:9.

"`Neither is there salvation in any other;
for there is none other name under heaven given among men,
whereby we must be saved.`"--Acts 4:12.

"`Wherefore, he is able also to save them to the uttermost that come unto God by him,
seeing he ever liveth to make intercession for them.`"--Heb. 7:25.

"`But of him are ye in Christ Jesus, who of God is made unto us wisdom,
and righteousness, and sanctification, and redemption.`"--1 Cor. 1:30.

"`Who his own self bare our sins in his own body on the tree,
that we being dead to sins should live unto righteousness:
by whose stripes ye were healed.`"
--1 Peter 2:24.

These few passages of Scripture will shew you the foundation of the Christian religion;
and if you are willing to attend to the divine law in your hearts,
your own experience will confirm to you the want and necessity of a Saviour,
that you may be redeemed from your sins.

And now, my dear young friends,
I shall conclude this letter with a few observations respecting your conduct.

In the first place, consider that the end and intention of your creation is,
that you should glorify God, which cannot be done, but by doing his will.
Endeavour then to love him above all things; and that this may be the case,
consider your religious duties as of the highest importance.

Do not neglect your meetings for worship; always attend them with cheerfulness;
and when there,
strive in silence to feel after the divine presence to comfort and instruct you.
Never encourage a thought that the time appointed
for this or any other religious service is misapplied;
for God`'s all-seeing eye can discover every thought as well as action,
and whether what we do is done grudgingly, or from a love to him;
and according to our works so will he deal with us.

Let the first day of the week be a day of religious improvement,
and not of idle dissipation.
Frequently read the Holy Scriptures, particularly on that day:
they are full of wisdom and instruction:
in them you will find that Joseph and Samuel were examples worthy of imitation,
when very young; for they loved the Lord above all things,
and he preserved and blessed them in an eminent degree.
If you read the Sacred Scriptures in a right disposition,
they will prove a confirmation to your faith and hope, a comfort and stay to your minds.
Never quote them in a light manner, or speak lightly of them,
or associate with those that do.
Endeavour, even every day, to read a portion of them the first thing in the morning;
and afterwards, inwardly and silently retire before the Lord,
and strive to seek his blessing, that you may be preserved from evil during the day.
And again at night, before you go to rest,
endeavour to recollect whether something may not have occurred,
that has been of an evil tendency; and if such should have been the case,
humble yourselves before him, and seek to be reconciled to him before you go to sleep.

Read also the writings of those of our own Society,
in order that you may cultivate an acquaintance with
the history of Friends and the principles of truth,
of which you are making profession.
In many of them you will be much instructed, and also strengthened to hold on your way,
by observing with what steadiness and fortitude they bore their testimony for the truth;
and some of them even unto death.

Be careful not to deviate from that plainness and simplicity of dress and manners,
in which faithful Friends have set the example;
having themselves found preservation and true peace therein.
A strict attention to this,
will be a great means of preventing your falling into snares you may be little aware
of The want of due care in this respect has lamentably paved the way for deep distress,
in many instances; and not to the individuals only,
but also to their families and connections.

Thus, my dear young friends,
you will be kept in the holy love and fear of your Heavenly Father;
and as you continue so to act, he will watch over you and bless you all your days;
and in the end you will be received by him into heaven,
there to enjoy unutterable happiness forever.
I am your affectionate Friend,

Frederick Smith,London, 12th Month 1805
