[#to-parents, short="To Those Who Have the Care of Youth"]
== To the Parents and Others who Have the Care of Youth in the Society of Friends

[.chapter-subtitle--blurb]
By Frederick Smith

[.salutation]
Dear Friends,

The education of the children of our Society has
been the subject of my most serious thoughts,
and I have often and earnestly desired it might be taken up by
some person whose qualifications would have enabled him to do it
more justice than I suppose myself capable of rendering it;
but no individual having stepped forward of late years,
to bring into view this truly interesting concern,
I have ventured to throw a few hints together,
in order that the matter may be deeply considered
by those on whom rests the care of the rising generation.

Though I had intended the principal part of what I may now
communicate for the consideration of school-masters,
school-mistresses, and other instructors of children,
yet I feel it a duty to say something also to parents.

It is a complaint which I fear is made with much justice,
that many parents are too negligent respecting the
religious education and instruction of their children;
too careless and inattentive in watching over them;
and too little solicitous that the seeds of those pernicious weeds be destroyed, which,
being overlooked, spring up into pride, ambition, and irreligion.
Nor are even some of those from whose situation in the Society
we might have looked for more lively care and regard,
always exceptions to this sorrowful complaint.

It must be obvious to those who will look impartially
at the outward appearance of our Society,
that it has lost much of that plainness which distinguished our ancestors;
and that many of late years have shown so increasing
a tendency to conformity with the world,
that were as great alterations progressively to take place,
I fear but few vestiges would ere long remain,
of that simplicity which the truth leads into; and which has been as a way-mark to many,
and the means of incalculable preservation to the dear youth of both sexes.
But I am grieved to add,
that I apprehend this declension is much to be attributed
to the spiritual weakness and indulgence of parents.
Having yielded to the youthful inclinations of their children,
they have paved the way for their gradually uniting with the pleasures, fashions,
and maxims of the world; which, in their natural consequence,
lead to a total distaste for religious duties-- a distaste to those very
pursuits and employments which should yield them the purest delight.
Ah! my friends, let us pause awhile,
and examine within ourselves whether these things are not so;
and whether our own peace and the eternal happiness of our beloved offspring,
are not concerned in our immediate endeavour,
to check an evil fraught with such imminent danger.
Our own experience and observation must have clearly shown
us the great advantage of keeping within the safe enclosure;
for herein preservation from many hurtful things has been known.
Nay, may it not be said to be one means of preparation for the work of the Lord Let
this experience then animate us firmly and steadily to restrain those feelings,
which tempt us to grant to our dear children,
liberties that the truth will not sanction--feelings which we may be assured
have only the semblance of true love or true affection.

I believe it will be allowed,
that there never was a time when it appeared more necessary for individuals,
in every part of the Society, to be diligent in endeavouring to build its waste places:
and perhaps, if this work be rightly set about, it will be found,
every one must begin in earnest at his own house.
The evils which we feel may be continually deplored;
but lamentation and exclamation will do little towards effecting this desirable end.
We must put shoulder to shoulder,
and individually exert those powers with which Divine
Goodness would not fail to supply us.

The recollection of most who have been favoured with truly religious parents,
if they look back at their early youth,
will convince them of the powerful influence such had over them;
more especially when they laboured to inculcate sentiments of religion and virtue.
May we not then, dear friends,
expect that the same effect would be produced by
our circumspect walking before our beloved offspring,
and thus labouring with them.

The minds of children are tender and susceptible;
they feel the force of advice and counsel affectionately
communicated by those whom they love;
the good effects of it are seldom, if ever, totally eradicated;
and the ground-work being thus laid by precept and confirmed by example, would,
I believe, in most instances, be blessed, sooner or later,
to the anxious and pious parent.

A religious education is the richest gift a parent can bestow on a child:
the want of it can never be made up by any wealth it may be in his power to leave him.
The love of parents never shows itself to so great advantage,
as when they appear solicitous for the religious welfare of their children;
and it is remarkable that there are scarcely any persons, even of those who are,
as to themselves, careless respecting this important matter,
but who are occasionally desirous that the seeds of virtue
and goodness may be implanted in their children.
This desire is observable when their children return from school.
If religious and moral principles are not then apparent in them,
blame is often attributed to the school-master; when,
did the parent look into his own breast,
he would discover that neither by precept nor example,
had he taken early pains to encourage those dispositions,
he now perceives would have been peculiarly desirable in his child.
The situation of a parent under such a circumstance, is an awful one;
and many have found it so, when it has been too late to remedy the evil.

I therefore earnestly desire,
that such parents as have young children yet uncontaminated,
may feel a living and constant concern to avoid the danger of their
children`'s blood being required at their hands.

I believe that little more need here be added to parents,
than the following excellent advices, extracted from the Epistles of the Yearly Meeting.

[.embedded-content-document.epistle]
--

We do with earnestness recommend to all such parents as have
experienced the gracious dealings of the Lord with their own souls,
to take all proper opportunities of instilling into the minds of their children,
just sentiments respecting the vanity and emptiness of fading and transitory enjoyments;
and to direct them to seek after that solid peace and serenity of mind,
which attends the sincere practice of true religion and virtue,
and which only can afford any durable, solid satisfaction.--Epistle, 1745.

[.small-break]
'''

And ye parents,
be ye solicitous to discharge your important and awful duty with scrupulous attention.
It is often too late to warn the youthful mind of danger,
when your own negligence or indulgence hath suffered
your offspring to deviate from that path of simplicity,
in which you have thought yourselves bound to walk, and in which you have found peace.
If you fail to suppress the early beginnings of undue liberty,
how can you expect a blessing on your endeavours
when further deviations at length arouse your attention?
and how, having failed to rule your own houses well,
can you expect duly to '`take care of the church of God,`' by performing
that too much neglected duty of private admonition therein.
There were of old those who brought children to Christ in the days of his flesh; and now,
the religious parent can breathe no warmer aspiration for them,
than when he spiritually commends his tender offspring to the protection of his Lord.
But see, Friends, that you encourage no propensities in them,
which prevent an union with him.
Restrain them, we beseech you,
from associating with those whose influence and example lead away from his law;
and be especially careful that you introduce not among them publications which are,
either wholly or in part, repugnant to the faith as it is in Jesus.
Let it be your own daily care to endeavour after closer communion with him,
and to walk in meek submission to his commands:
so may you gain over the minds of the youth providentially placed under your care,
that ascendancy which arises from the united effects of sound judgment, truest love,
and a good example.--Epistle, 1800.

--

Now as to those who undertake the tuition of the children of others,
they have a most serious trust committed to them:
the real well-being of such children greatly depends on their tutors`'
attention to their religious improvement.

Some parents wish their children to excel in literature.
To this, simply considered, there can be no objection;
but an education ever so brilliant, without the more important addition of true religion,
is deprived of its greatest excellence; whereas, with this blessed advantage,
a man will be rendered a bright example, and may become extensively useful.

Seeing then that the education of children is of so much importance,
I conceive it is highly desirable that those who undertake
so weighty a trust as the education of the children of others,
should themselves be "`men fearing God,`" and should engage in it from principle.

Let them make it their first study to live so near the Fountain of truth,
as to be able rightly to instruct them in their relation to their Creator,
and their consequent necessary and positive duty to him;
and also in the doctrine of salvation through Jesus Christ.
Their minds being thus imbued with religious reverence,
they would be prepared to receive the further opening of counsel,
on the benefit of frequent retirement in spirit, and abstraction from sensible objects;
for the renewings of divine favour and strength, to withstand temptation to evil,
and to qualify them to look up to the Lord,
and love him as the Fountain of all their blessings.

Religion, when thus properly implanted, would, with the divine blessing, become habitual;
or at least such a foundation would be laid, that,
though some of the youth might be so unwise as to
swerve from its wholesome and salutary dictates,
they might afterwards, like the repentant prodigal, retrace their mistaken steps,
might look towards their Heavenly Father`'s house in great self-abasement,
and through divine mercy, experience restoration.
On the contrary, young persons who have been neglected,
and have never known any religious instruction, either from parents or tutors,
seem in a most deplorable state;
and will have good reason to reflect upon those whose first business ought to have been,
to instil the principles of true Christianity into their minds.

O that those who engage in the education of the youth among us,
were firm in all their proceedings respecting them; and would, as much as in them lies,
avoid running the hazard of their school becoming contaminated,
out of favour or affection to any negligent parents, by permitting loose examples,
either in manners, dress, or address, inconsistent with our holy profession!
If a stand in this respect were made,
I am persuaded much advantage to the rising generation would result from it.
Those who, from a principle of duty,
endeavour to preserve this order in their establishments, will, I believe,
find abundant support in the rectitude of their conduct;
nor could those parents who had the real welfare of their children at heart,
reasonably object to the adoption of a plan which had the
principles of their profession for its foundation.

In addition to this,
no books should be introduced into a school until perused by the master or mistress;
but such books should be provided as tend to convey
instruction to their susceptible minds,
in an agreeable and alluring manner: always avoiding those which,
however otherwise instructive, have the least tendency to subvert,
or even indirectly to attack the truth as it is in Christ.

But above all outward means of instilling religious knowledge, do not fail, dear Friends,
to make the Sacred Volume a frequent object of your children`'s or your pupils`' attention.
You will find it an advantage to have your families daily
assembled for the purpose of reading a portion of it.
In doing this, care should be taken, that so much be not read at a time,
as to prove tedious to young and active minds;
and also that attention and a decent stillness of behaviour prevail while thus engaged.
A moderate pause on leaving off, will afford time for digesting what has been read,
or for indulging such sensations of reverence as may have been excited;
and if you endeavour to keep your minds low, and dependent on heavenly instruction,
you may sometimes be enabled profitably to explain
what has occurred that may not appear obvious;
or otherwise speak a word in season,
and so implant some good principle in the youthful breast.

One day in the week is more especially set apart for the purposes of religion.
Let that day then, without lessening their attention to religious duties at other times,
be appropriated to them;
and let all those engagements be excluded which do not comport with this practice.

Some part of what I have been saying,
may be in degree applicable to those who have the care of youth more advanced in years,
namely, servants and apprentices.
I well know it is sometimes difficult to use that
restraint towards young people of a lively disposition,
which nevertheless is really necessary.
They are oftentimes influenced by the example of some of their own age,
whose parents or others have permitted them to take undue liberties;
even so much so as to abandon that becoming simplicity of manners for which we,
as a Society, are remarked.
But, dear Friends, be assured your firm and steady care over the youth of this class,
will meet with its reward.
Only reflect on the gratitude thou wouldst feel towards that friend,
who considered thy child as his own, and who, by precept, example,
and that restraint which arises from love alone,
had done all in his power to preserve thy child from the contamination of the world.

To conclude.--What occupation in this life can be more honourable than theirs,
who carefully and successfully attend to the religious improvement
of youth Those who have been thus engaged to fulfill their duty,
must have a solace in their minds,
far beyond any earthly advantage they may reap by their outward profession;
whilst the sincerest gratitude and love, both from the parents and the children,
cannot but be excited towards them.

[.signed-section-closing]
I am your affectionate friend,

[.signed-section-signature]
Frederick Smith.

[.signed-section-context-close]
London, 13th of First Month 1806
