[quote.epigraph, , Phil. 3:7]
____
What things were gain to me, those I counted loss for Christ.
____

== Introduction.

THE following Memoirs are extracted from manuscripts found in Frederick Smith`'s hand-writing,
after his decease.
They were printed in The Friend, (a Monthly Journal,) in the year 1845;
but as they are considered to be of too interesting and instructive a
character to be restricted to the columns of a periodical publication,
it has been concluded to reprint them in the present more permanent form.

The power of divine grace is eminently displayed in the conversion of
such as have been grievously entangled in the snares of folly and vice;
and their deliverance is calculated to encourage those who
are concerned in christian love to deal with transgressors,
to persevere in their endeavours to reclaim, with a hopeful mind;
it also tends in a peculiar manner,
to excite feelings of grateful admiration towards that compassionate Saviour,
who is "`the Healer of the breach--the Restorer of paths to dwell in.`"

The case of Frederick Smith presents a remarkable
instance of the efficacy of this renovating power;
not only as it enabled him successfully to contend against his many evil propensities,
but also as it conducted him through many singular trials and difficulties,
to a settlement in the truth.
Of this he appears to have been himself deeply sensible;
and under the humbling conviction that he had been "`forgiven much,`" he manifested
by his zealous endeavours to promote the cause of truth and righteousness,
that he "`loved much.`"

His two "`Letters,`" which conclude this little compilation,
have passed through three editions as tracts;
yet as it is probable that the present volume may come into
the hands of many who have not met with them before,
and as they are well calculated to promote that greatly
important object--the best welfare of the rising generation,
they are now appended to the Memoirs.

It is to be regretted that Frederick Smith did not continue
his auto-biography later than about the year 1800;
for although his latter years may not have furnished incidents so remarkable
as those which occurred in the earlier part of his life,
yet doubtless the Memoirs might have been continued instructively,
as regards his further religious experience and service.

T+++.+++ C.

Kingston, 4th Month 1848
