== The Life of Fredrick Smith

I was born in London, the 28th of the Sixth Month, 1757;
and before I was five years of age, was put to a boarding-school.
I was naturally of a lively disposition, and very early susceptible of evil impressions;
so much so,
that I have frequently looked back with admiration
to observe how soon the enemy makes his inroads.
In general, the morals of children are not so much attended to as is requisite,
in seminaries of this kind,
and I very early contracted vicious habits from the example of the other boys,
which every day ripened.
Could I have seen myself, or have been seen as I really was,
the increasing deformity of my mind would doubtless
have discovered me to be a little monster of iniquity.
Before I was nine years old, there was scarcely an evil incident to children of that age,
with which I was not acquainted, and which I had not a hankering after;
though I believe I sometimes had some serious thoughts, but they were so transient,
that I hardly recollect them.

When I was about thirteen and a half years of age, I was taken from school,
and sent to London to occupy a situation under Government, in the General Post Office;
where I found several lads about my own age.
A near relation was Comptroller,
and his brother held another situation in the same office: I was under their joint care,
they having kindly undertaken to watch over me.
I lived with them and their sisters; but as they had not room in their house to lodge me,
a respectable lodging was provided for me in the neighbourhood.
My relations were opulent people,
and kept a great deal of what is called fashionable company;
yet they did all they could to restrain me from following
those evil propensities I so much delighted to indulge in;
and they frequently rebuked those who visited them, when they made use of oaths,
or introduced any wicked conversation in my presence.
They were ignorant of the progress vice had made in my heart,
and endeavoured to prevent the evil seed from being sown.
But alas! the work was begun; and being associated with so many young lads,
most of whom were under little or no restraint,
while together we gave loose to our various inclinations; and I am ready to conclude,
that from the age of fourteen till I was twenty,
there were few who exceeded me in vicious conduct.
The enemy, during these years of my youth, had strong hold of me;
there was scarcely an evil gratification which he did not allure me with.
My relations frequently remonstrated tenderly with me,
and pointed out the consequences of my pursuing vice in the manner I did;
but withal were as kind parents to me,
endeavouring to heal rather than expose my weaknesses.

During this time for several years I did not enter a place of religious worship,
except for some wicked purpose;
yet I never lost sight of a sort of idea of a Supreme Being, and I believe,
never went to bed without endeavouring to say my prayers;
often even when stupified with liquor, I waked in the course of the night or morning,
and performed this apprehended duty.
This I consider to be a strong proof of the beneficial effect of parental care,
in endeavouring early to impress on the minds of youth, day by day,
their duty to their Creator.
This will, in most instances, as it did in me,
preserve a chain of religious thoughtfulness and reverence to the great First Cause;
it may often be as seed sown, which in time may expand,
and from it the knowledge of divine things may be permitted to increase.

During this career of wickedness, there seemed +++[+++but little]
to hinder my putting what was in my heart into execution;
and as to what the world calls pleasure, I knew no restraint,
the enemy continually finding out fresh food for my sensual appetite.
At intervals I providentially found a stop, and the language passed through me,
"`Surely it will not be always thus with me--I shall at some time or other be caught
in the trap of the enemy;`" but such impressions lasted only for a few minutes.
I remember once being so convicted in my mind, of the progress sin was making in me,
that I flung myself on my bed, burst into tears, and cried to the Almighty for help.
I was made sensible of the deplorable situation I was in, and said within myself,
"`Surely the enemy will overcome me at last,
and I shall become a shame and disgrace to my family and myself.`"
I strongly felt my depravity and weakness,
and fervently prayed for help and strength to resist evil,
and for forgiveness for my past wicked conduct.
But this impression did not last a great while; I soon returned to my evil courses.

Owing to the kindness of my relations, at whose expense I lived,
the greater part of my salary was given me for pocket-money;
so that I never troubled my parents for money, and they were ignorant how I went on.
When I visited them in the country,
on leaving them they used to give me very wholesome advice;
and by their affectionate solicitude they so wrought upon me,
as to make me resolve in my own mind, to be more circumspect in my conduct,
and to leave those companions to whom I was as injurious as they were to me.
A few days after my return to London, all these tender impressions would be obliterated,
and I returned with redoubled vigour to an abandoned life.

Having received a fashionable education,
and been instructed in all the accomplishments which, in the view of the world,
constitute the gentleman, such as dancing, fencing, etc.,
I was equal to most in superficial knowledge,
and was introduced into much fashionable company.
I frequented balls, the theatres, musical entertainments,
and other equally unprofitable amusements, till my twenty-first year; when,
without the consent or knowledge of my friends, I married.

In consequence of this rash act, I had now to struggle with some difficulties;
for so far from having made provision for a step of this sort, I had,
during the last year or two, been so extravagant as to contract debts, which,
though not to a great amount, were the occasion of considerable embarrassment.
Some heavy family afflictions, which occurred at this period,
brought me to a degree of recollection,
and this was much assisted by the prudent demeanour of my wife,
who although she had consented to our marrying clandestinely,
yet carried herself so circumspectly as completely
to wean me from all my dissolute companions;
and thus, through her means, under Providence,
I was mercifully rescued from apparent certain ruin.
Though most of our friends were disconcerted at the step we had taken,
yet in a little time they became reconciled,
and kindly assisted to increase my outward means:
and as we were contented in our humble situation, and satisfied to live very frugally,
also happy in each other, we were, as to outward matters,
comfortable beyond our expectation.

About the year 1780, I had, at times, some serious impressions,
and seemed to lack something which outward enjoyments could not afford.
For some time I attended the national worship; but not being satisfied,
I frequented the meetings of Methodists and other dissenters:
and though I apprehended these were more zealous and sincere
than the generality of those of the church of England,
yet my mind was so conscious of the deep wound which sin and corruption had made,
that I was persuaded no superficial attempts could heal it;
and I had a prospect of something beyond all that I had yet seen or heard,
though I could not then describe the whole of my feelings,
except as they were brought into action.
I was still a strange jumble of inconsistency;
for some things of a gross nature remained with me.

In the year 1782, I was subpoenaed by the Post Office to give evidence at the Old Bailey,
against a man for robbing the mail; and during the time I was in waiting,
I could not but take notice of the poor man`'s countenance,
which seemed to exhibit a picture of distress.
In an instant, as it were,
my mind was filled with a variety of reflections on the nature of the crime.
Surely, thought I, if +++[+++as respects myself]
retributive justice were to take place, I should be placed where the criminal now stands.
He perhaps has committed this crime through necessity;
probably he has not had the advantage of a good education, kind advisers,
or any to instruct him in that which is good;
while I have been cared for from my early youth:
my parents have often warned me to refuse the evil and choose the good;
they have given me a good education, and I have had many advantages denied to others;
yet such is the depravity of my heart,
that for years I have been leading a life of continued dissipation and folly.
In thus viewing myself as compared with the prisoner at the bar,
I was so struck with abhorrence of myself,
and the sight of the dreadful precipice on which I had been standing,
that I shed abundance of tears.

A circumstance occurred during the trial,
which excited in me an additional degree of thoughtfulness.
One of the witnesses gave evidence which, though of no great importance, was not,
in point of fact, correct; and had I been called upon,
I should have been obliged to contradict him.
This circumstance led me to consider the nature of an oath;
that it was a solemn appeal to the Almighty that
the matter then about to be asserted was the truth;
that under such circumstances,
(especially when the life of man is concerned.) an oath appeared to me of so much importance,
as to make it highly improper to use one without a strong conviction of its solemnity.
In fact, I began to doubt whether the taking of an oath is,
under the christian dispensation, justifiable;
for though but little versed in the Scriptures, I recollected that Jesus Christ had said,
"`Swear not at all.`"
I was thus brought into a most trying situation, under the feeling of which,
I earnestly supplicated the Almighty that I might
be excused from giving evidence in this case;
and in great condescension and pity to my secret cries, he heard me,
and I was not called upon.
Under a deep sense of my own unworthiness and the goodness of my Heavenly Father,
I resolved, with his assistance, to follow him wherever he should lead me.
I left the court full of joy and gratitude, and in my feeble way,
endeavoured to render the praise where it was due.
Although thus seriously impressed on the subject of swearing, it is remarkable,
that the impression had little or no effect in turning
me from the foolish and wicked practice I was in,
of profane swearing, and taking the great and holy name of God in vain.

About this time I was brought to a serious recollection
of the many gracious visitations of the Almighty to my poor,
wicked soul, and particularly his answer to my prayers;
not only in the instance before related, but also in two others,
during the dangerous illness of my dear wife,
when I had earnestly and with many tears besought him to relieve her pain,
which was very great, and continued for many hours, and it immediately ceased.
I also began more plainly to see the natural proneness there was in me to evil,
(in common, I imagine,
with all the human race;) this I could trace back in myself to a very early age,
and could recollect some instances of sinfulness
and depravity which even then filled me with shame.
Thus was I introduced to a view of the degraded and fallen state of man by nature;
and feeling my inability of myself to overcome my evil passions and inclinations,
I was led inwardly and fervently to implore divine help and instruction.
Frequently while walking in the streets I have lamented
that the churches (so called) were not opened,
as in the countries where the Roman Catholic religion prevails,
that I might pour out my soul before the Lord,
and praise him for the love which he had begotten in my soul;
being ignorant that he does not (exclusively) "`dwell in temples made
with hands;`" though I could not find the peace I was desirous of obtaining,
when I attended the common worship in those places; which appeared to me extraordinary.

I had been in this seeking state for some time,
when I became acquainted with a person belonging to the Society of Friends,
who lived near us, at Walworth;
whose company seemed very different to what I had been used to.
A few months previously, the Quakers being mentioned in the course of conversation,
my wife said, if ever she changed her religion, it should be to a Quaker;
to which I replied, that the Quakers were a set of fools, and had no religion in them.
But now I was of a different mind; and I requested the Friend above alluded to,
to lend me some book relating to his principles, which at first he refused.
Afterwards, with some reluctance, he lent me Barclay`'s Apology,
cautioning me at the same time against too much earnestness in the perusal,
and setting down as truths the sentiments of the author,
till I had sufficiently weighed them in my own mind; adding that he believed with Peter,
"`that God is no respecter of persons,`" but that those of all
religious denominations "`who fear him and work righteousness,
are accepted of him.`"
I have often looked with much satisfaction at this conduct of the Friend,
in not laying hands suddenly on me,
and considered it a proof of his prudence and kindness; and indeed the kind,
parental care and solicitude for my spiritual welfare,
manifested by himself and his wife,
though I was not within the pale of their religious belief, instanced such a liberal,
tolerant spirit, and freedom from bigotry,
as convinced me that Friends were got far beyond
most others in the substantial part of religion.
I read the book with much attention,
and was surprised to find that the fundamental part so exactly corresponded with
the idea I had formed of the union that subsists between God and his creatures.
I was also much instructed many ways,
especially respecting the meaning of the words Holy Spirit,
of which I had before been totally ignorant, as, I have reason to fear,
is the case with thousands, who call themselves Christians: I could have said,
as some did to Paul, "`We have not so much as heard whether there be any Holy Spirit.`"

One day, while I was reading Barclay`'s Apology,
I told my wife I believed I should turn Quaker,
the book I was then reading having opened my understanding respecting religion,
more than any book I had ever read; and that it was throughout so simple,
and corresponded so exactly with the Scriptures,
that it appeared to me to be the very truth,--or something to that purpose.
She appeared to be much distressed at my expressing myself thus; and from that time,
did all in her power to divert me from my purpose.
This I was much surprised at,
as I had buoyed myself up with the hope that she
would as gladly receive the truth as myself;
ignorantly supposing that it was only for lack of the knowledge of a better way,
that people remained in the form of godliness,
without appearing to know anything of the power.

I had now found the pearl of great price.
My wife tried many ways to prevail with me to alter my purpose;
and at last with many tears entreated me to desist,
telling me that her health was much impaired by her uneasiness of mind;
(which I have reason to believe was really the case;) at the same
time pointing out to me the danger of our circumstances being materially
injured by my losing my situation in the Post Office,
and the distressing prospect of our becoming estranged from each other,
and our children divided,
by my persisting in the intention of belonging to
a different persuasion of religion from herself.
I was at this time in the practice of attending the meetings of Friends;
but these arguments, together with the love I bore to my dear wife,
induced me to promise her I would not attend them any more.
I kept my word for a week or two,
and for a while absented myself from the Friend`'s house who had been so kind to me.
But I had no peace herein; for having found the pearl of great price,
I soon perceived it would be necessary to sell all that I had,
if ever I meant to purchase so choice a treasure.
In a short time I secretly called on my friends as before,
and borrowed John Richardson`'s Journal,
which was the first book of the kind I ever read;
and I was surprised to find there were any persons of so late date
who approached so nearly to the character of the saints of old;
not being aware at that time, of the universal efficacy of redeeming love,
and that this principle will, in all ages, produce the same effects.
At this discovery I was much humbled as well as encouraged:
and I now determined that nothing should hinder me from pursuing
whatever I apprehended to be the mind and will of God.
My wife soon became acquainted with my determination,
which was cause of much unpleasant variance between us:
her aversion to the change induced her to oppose me in every way she could; and I,
as yet unmortified and naturally hasty, was impatient of contradiction;
so that we knew very little condescension on either side.

I was now called upon to give some proof of my love
to Him who was thus graciously visiting me.
I was subpoenaed to give evidence in one of the courts of Westminster,
respecting a person`'s hand-writing, to which I had been a witness.
This brought me into a great strait; for I felt that I dared not take an oath;
and my refusal, which could not be kept secret,
I apprehended would endanger the loss of my situation.
I called on my kind friend, to advise with him.
He saw my difficulty, and I believe, felt for me in my distressed condition:
but it seemed out of his power to assist me.
He took me, however, to another Friend, an elder, who, he said,
had a good deal of knowledge in matters of this sort; but alas! it was to little purpose;
and I was taught that, in cases of difficulty, it is not to man we must look for help.
I then waited on the attorney, told him the difficulty I was under,
and endeavoured to prevail on him to get some other person in my stead.
But he could afford me no relief,
except that he asked me if I could take the Quaker`'s affirmation.
I told him I did not know what it was; but when he showed it to me, I felt no objection.
He therefore promised to prepare the way for me in the court,
that I might have as little trouble as possible.
During the time I had to wait in and about the court before I was called,
which was about eight hours, I was exceedingly distressed in my mind.
On being called, I informed the court I could not take an oath,
and the affirmation was immediately offered to me.
I instantly felt such a flow of peace and comfort to my poor, tried mind,
as I had never experienced before; and I seemed so elevated,
that everything about me appeared different from what it had before:
it seemed as though I saw a new heaven and a new earth, that all things had become new,
and all things of God: and I returned home joyful,
and strengthened with the enriching balm of heavenly love in my bosom.

Although this event terminated so favourably, yet it seemed probable,
that in consequence of my objection to taking an oath, I should, at some future time,
lose my situation under government.
This was a continual exercise to me;
and it seemed desirable that I should be prepared for such an occurrence:
and having an opportunity of laying out my property in merchandize,
without much consideration, I embraced it.
This step laid the foundation of much future difficulty.
At the earnest request of my wife,
I also engaged in partnership with a near relation of hers; which I was induced to do,
principally from a desire to convince her that I
was willing to do all in my power to make her comfortable.
This person had been imprudent, and had become involved in his affairs;
but as I was informed it was not to a great amount, and my income was handsome,
I hoped to be able by this means to extricate him from his difficulties,
as well as by attention to business, to do something for myself.

I had not entered into this engagement many weeks,
before what I had anticipated +++[+++relative to my objection to take an oath]
took place.
I was again subpoenaed to give evidence against a man who had robbed the mail.
In this case the affirmation would be of no avail; and I very soon learned,
that if I refused to take the oath, I should most probably lose my place.
My distress was now very great;
for I had discovered that my partner`'s affairs were
in a worse state than I had before understood.
I had become much encumbered; and having but little knowledge of trade,
I was soon plunged into great difficulties.
Thus I had not only the prospect of losing my situation,
but with it my only means of extricating myself from my difficulties,
and carrying on my business;
so that I was now likely to be left in a worse situation
than if I had not embarked in trade.
Under these distressing circumstances, the first step I took,
was to represent my situation to my relation, the Comptroller of the Post-office,
in order that, by being thus timely apprized of my objection to take the oath,
they might have opportunity of doing what they conceived to be right,
towards promoting the course of justice in the affair;
and I requested that he would inform the Postmasters-general.

The Comptroller and his brother were greatly affected; they considered me as their child,
having brought me up from my youth, and treated me with parental affection.
I was rapidly getting forward in the situation I held;
and to see my fair prospects thus blasted, and that I was obstinately bent,
not only on my own ruin, but also that of my family, was a great disappointment to them,
and grieved them much.
They tried to persuade me to alter my resolution, but in vain;
and the Comptroller reluctantly complied with my request.
The kindness of my relations at this time, was more than I could well bear,
and was a greater trial to me,
than all the threats and unkindness of my superiors in office.
I was interrogated by the Secretary and Solicitor, and threatened by them,
that if I did not comply, I should be imprisoned.
By order of the board, I attended at the Post-office,
to give my reasons to the Postmasters-general, the Earl of Tankerville and Lord Carteret.
I was treated with much unbecoming rudeness,
and endeavours were used to have me instantly dismissed:
but the Solicitor informed the board that this could
not be done till I had been put upon my trial,
whether I would take the oath or not.
I was therefore ordered to attend at the assizes
at Aylesbury on the 8th of the Third Month,
1784.

Owing to a combination of circumstances of a very trying nature,^
footnote:[Among these was an accident my little girl had met with:
the nursemaid carelessly allowed her to fall off the bed,
which occasioned the formation of an abscess inwardly, and a consequent gradual decay;
so that she became reduced, to all appearance, to the last stage of a consumption.]
I was at this time very much distressed; and under the pressure of my afflictions,
I wrote the following letter to +++[+++my friend at Walworth]:--

[.embedded-content-document.letter]
--

[.letter-heading]
To James Maddocks, Walworth.

[.signed-section-context-open]
Haymarket, February 10th, 1784.

[.salutation]
Dear Friend,

I think I never, in the whole course of my life,
sat down to write when my spirits were in so unhappy a state.
We may boast, and really imagine ourselves capable of enduring every possible misery;
but our minds are, in general, too susceptible of buoyant impressions,
and till experience shows our weakness herein,
we bid defiance to the mutability of human life.
While meeting the casual accidents which attend mankind,
we are too apt to lose sight of the intention of Providence,
in thus reminding us that our dependence ought to be solely on God.
Such, I fear, has been my case; for,
had I made proper use of the many kind admonitions
and gentle reproofs with which I have been favoured,
I should not now be left to the agonizing tortures which I too sensibly feel.
The quick progress of my misfortunes, and the time of their commencement,
would at most tempt me to doubt whether I am acting right,
did not the assurance in my breast bring that matter to a certainty.
My little girl came home to us this day, very ill with the measles, which,
added to the other complaints, occasioned by the distressing accident she met with,
gives us reason to fear her dissolution will be rapid; and yet I cannot but hope,
if she can but combat this last, she will get the better of her other disorders.
A matter of some consequence to my temporal affairs has occurred, which, I believe,
must bring my affairs to a crisis.
Some time since, the Liverpool bag of letters was missing,
and it happened I was the only person in the office on the day it should have arrived,
whose business it was to take particular notice of the affair.
A man is now in custody for the robbery,
and I am ordered to attend as a principal witness on his trial.

You see how I am situated;
and though I thought myself before sufficiently encumbered with misfortunes,
it is my lot, I fear, to have many more to encounter.
O! the world, this miserable world! it is on that my heart has been set;
for were I pure and upright in the sentiments I profess,
I should doubtless be happy in this opportunity of a voluntary sacrifice.
Look at my situation my dear friends;
my little all ventured to America and no prospect of a return;-the
adventure with my partner likely to prove as unfortunate;--a
child dying;-and my other means likely to be torn from me,
because I will not prove treacherous to my God.
But above all, the distraction of my family engrosses my attention.
To them, all my actions appear as folly and madness;
nor can all the arguments I make use of convince them to the contrary,
considering as they do,
that my misfortunes arise from a determination to
pursue what will eventually terminate in my ruin,
but which I fallaciously think will lead to happiness;
and that since heretofore the Almighty had blessed me with abundance,
when my conduct was in every respect different,
it proved that he was perfectly satisfied with me; that consequently,
the course I am pursuing is sinful,
and that these are just judgments for the wrong steps I have taken.
It is impossible for one individual to judge of the inward state of another`'s heart,
nor how far there may be a necessity for an alteration in his conduct.
At present I am wholly at a loss how to act, with regard to my affair with my partner.
I undertook it on the presumption of my income at
the office assisting towards discharging the debt;
but that income, I fear, is no more.
To God alone I submit myself, and he alone can relieve my distress; nor have I a doubt,
notwithstanding the unfavourable appearance of things,
that I shall yet meet every comfort from him.
If you can spare time to write me a few lines, I shall take it as a favour.
I would call on you, but think it would give uneasiness at home.
With kindest love to you and yours, I remain your sincere friend,

[.signed-section-signature]
Frederick Smith.

--

[.offset]
In reply to the foregoing, I received the following truly acceptable letter:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Walworth, Second Month 12th, 1784.

[.salutation]
Dear Friend,

Your very affecting letter of the 10th instant is received.
The multiplicity and weight of your present afflicting trials may well affect your spirits:
we are struck with awful feelings at your manner of expressing your sufferings,
and pray that He who permits them, will be pleased to support you.
His will must be submitted to in all his dispensations.
We receive good things, and we ought not to murmur at what may appear evil.
We hope you will experience Divine help.
+++[+++Our heavenly Father]
never forsakes those who trust in him; but if He require all to be given up,
we must submit and prove ourselves worthy.
We hope these grievous appearances will disperse, and consolation be afforded.
Perhaps your child may be restored,--and the American affair turn out more favourable
than you at present may fear.--The Post-office affair is,
I confess, a matter of great consequence,
but possibly may not be attended with the effect you naturally dread so much.
Is there no possible relief to be obtained by applying to the Postmasters-general,
or Secretary, to excuse your appearance,
either by your own or some friends`' interest with them,
to prevent the disagreeableness of what will be the consequence in court.
If I can be of any service in any shape in my power, it will be a great pleasure to me.
The concern in the Haymarket I leave at present;-the
frowns of your relations are not much to be feared;
you are superior +++[+++to them],

[.signed-section-closing]
I am your sincere friend,

[.signed-section-signature]
James Maddocks

--

Previous to my going to Aylesbury, where the assizes were held,
my dear child was restored to us, which I considered a great favour.
The measles caused so great a revulsion in her constitution,
that in a few days after the eruption appeared she began to revive;
and in a few weeks she recovered.

At this time, however, my wife was taken seriously ill,
occasioned by the distress of her mind in viewing the awful prospect before us,
and the uneasiness my conduct had given her; which was not to be wondered at,
seeing that what I did to procure peace of mind to myself,
appeared to involve her and our young family in ruin.
She was so ill on the day I left her,
that the physician who attended her expressed his fears of her recovery.
I was however obliged to leave her, and I took my farewell of her under much affliction,
having great cause to fear we should never meet again in mutability.
This was on a First-day.
I went to Westminster Meeting in the morning,
when a Friend asked me if I had been recommended from the meeting I came from.
I replied that I did not understand what he meant;
that I was not a member of the Society of Friends, whatever I might hereafter be;
that I was then about to set off for the Buckingham assizes, where,
on account of my refusal to take an oath,
I expected to be deprived of all I possessed in this world.
The Friend seemed affected, and said he had observed me so constantly attend meetings,
and sit so solidly in them, that he thought I had been a member.

I accompanied the Solicitor to Aylesbury; he behaved kindly to me,
and the company who were collected there showed me more respect than I had expected.
A circumstance occurred during my stay, which afforded me much instruction.
Having been at several meals with those who came there to attend the trial,
I was thankful in observing more decency than is usual in mixed companies,
especially after dinner and supper.
Two persons were present who had been members of the Society of Friends,
but were disowned, one a member of Parliament, the other a merchant.
The former expressed to me his love towards the Society;
but I had afterwards good reason to doubt his sincerity, at least as it regarded myself.
The last evening but one that we were together, the Solicitor,
who sat at the head of the table, desired us to fill our glasses;
but having all along felt a particular objection to countenancing drinking,
I had uniformly refused toasts; and now being urged more than usual,
I gave them my reasons for refusing.
Still, however, the company continued to press me;
and to prevent further solicitation I filled my glass with water only.
This answered their purpose;
and a scene of as great indecency and confusion followed as I had ever witnessed.
A clergyman, who was also a magistrate in the county,
was more wicked and obscene than the rest; and to my astonishment,
I observed the Member of Parliament, whom I had considered as my friend,
ridiculing the distress I was not able to hide.
I took my candle and went to bed,
lamenting that in all probability I had been the cause of it;
for had I remained firmly attentive to my inward feelings,
I might have been instrumental in convincing those
present of the folly of the practices they were in.
But it was now too late,
and all I could do was to learn experience from the things I had suffered.
It was a lesson that I have often recurred to,
when my resolution has been tottering under trials of faith and obedience.
In the morning I found out some Friends in the town, who were kind to me;
and I became acquainted with a young man named John Grant, who was also subpoenaed.
In his company I spent the remainder of the time I had to stay
at Aylesbury less unpleasantly than I otherwise should have done;
and we were afterwards much united in religious fellowship.

And now the time came for me to manifest my love to Him who had allured me out
of Egypt into the wilderness--who had spoken peace to my guilty soul,
and had forgiven my many transgressions and backslidings.
Under a sense of these mercies, I appeared in court; and when I was called,
I told the judge, without hesitation, that I could not take an oath; which having done,
my heart seemed to overflow with sweet peace,
and I was strengthened to bear the scurrility and the ill-natured remarks of a counsellor,
who had no doubt been hired for the purpose of making me appear odious to those present,
and to give the Postmasters-general a plea for displacing me.
He, however, so far overshot himself, that several of the counsel rose as one man,
and one on behalf of the rest pleaded my cause,
and requested that the counsel who had treated me so roughly might be desired to desist;
observing, that I had a right to refuse taking the oath if I chose it;
which the other attempting to reply to, the judge, with seeming displeasure,
told him to sit down, adding,
that it was the business of the Postmasters-general and not of the court,
to take cognizance of the conduct of their officers.
He then kindly asked me if I chose to take the oath; which I refusing to do,
he told me I might leave the court if I pleased,
as they had nothing further to say to me.
I immediately hastened home, where I found my wife much better;
and I had the abundant satisfaction to learn from her, that during my absence,
at the time she appeared in the greatest danger,
her mind was so filled with comfort and Divine love, that she longed to be dissolved;
and she believed that had she gone then, it would have been well with her.
This account filled my poor heart with gratitude to the Lord,
for thus remembering me in the midst of my deep probations;
for surely no one had greater reason to be humbled in the dust than myself,
an unworthy sinner.

Having been thus mercifully helped through so many difficulties,
I experienced a degree of strength to encounter fresh ones.
I was now in expectation of losing my place in the Post Office,
the justice of which I could hardly reconcile,
seeing that my refusal to comply with the requisition of my employers
was well known to arise from my adherence to integrity of principle,
and not from a desire to evade any part of my duty as a servant to the public.
I thought myself justified in using endeavours to
retain my situation on account of my family;
for though I had not lost all my property,
by far the greater part of what I had accumulated was now gone:
and in case of my dismissal I apprehended I should
be entitled to some compensation for past services,
my youth having been spent in the laborious duties of my employment.
I therefore used what interest I could with the Postmasters-general,
through the medium of my kind friend and relative the Comptroller.
This proving ineffectual, I thought it right to address the Secretary,
that he might use his interest with them.
I accordingly sent him the following letter --

[.embedded-content-document.letter]
--

[.signed-section-context-open]
General Post Office, March 17th, 1784.

[.salutation]
Sir,

It is with much regret I find myself under the necessity of giving you trouble;
but the circumstance of my having been obliged to attend the Assizes at Aylesbury,
and there practically to avow those sentiments which I conscientiously
believe to be perfectly consistent with the true principles of Christianity,
though not altogether agreeable to the opinion of those
who profess the established religion of this kingdom,
has rendered it almost impossible for me to avoid it.
It must be confessed, I am in a very disagreeable predicament on account of my family,
which urges me to request your kind interference
with the Postmasters-general on my behalf.
I am well aware of the necessity there is for every precaution to prevent
abuses in the management of the business of the Post Office;
and the present unfortunate affair may have suggested to you a new species of fraud,
which might hereafter be practised by parties whose
duty it might be to bring others to justice,
by pretending to be of the Society of Quakers.
It must be allowed that such a surmise may not be without foundation;
but if the character of the party, under circumstances of this kind, were considered,
the execution of such a fraudulent intention might be prevented.
I have been more than thirteen years (half my life) in the Post Office,
the duties of which, you are sensible,
are as laborious as those of any office under Government, if not more so;
and I believe I can add, without deviating from the truth,
that I have attended my appointment with fidelity and honesty;
for a confirmation of which I appeal to my brethren in the Office.

The earnest desire I had to do my duty to God as well as to man,
led me to search minutely into religion;
and my endeavours strictly to observe that duty will not, I trust,
be the means of criminating me.
My refusal to take an oath I really believe, is built on a sure and solid foundation.
I have therefore to entreat you to represent my case as it really is,
to the Postmasters-general;
and as matters of conscience have ever been considered by
true Christians to be of a very delicate and tender nature,
I cannot but hope they will look kindly rather than harshly on my conduct.
The duty I at present fulfill,
has very little connection with any other part of the Office;
consequently I shall not be subject to the inconvenience I have lately experienced;
and if I may be indulged by being allowed to remain in this employ,
I shall think myself amply remunerated,
and will give up the prospect of future advancement.
If, however, the Postmasters-general are not willing to grant me this favour,
I have only to beg that,
as there have been precedents of persons resigning
and receiving an annual stipend from the Office,
they will be pleased to grant me the like indulgence.
I am, with respect, your obliged friend,

[.signed-section-signature]
Frederick Smith.

--

In a few days I was ordered to attend the Board;
and though the Postmasters-general appeared more mild than they had done,
yet I met with no success from my application.
I was told I should not be immediately dismissed,
as I had represented how I was circumstanced in other matters,
but that I should have liberty to attend the Office as usual for two or three weeks,
till I could turn myself about.
But I was much surprised and disappointed the next morning, when on entering the Office,
I was told that it was the express order of the Postmasters-general
that I should not do any more duty;
and I was refused even the indulgence of going to my drawer.
This appeared the hardest of all my trials.
It was unexpected; and I could not but sit down in my room and weep aloud.
I was informed that orders were also given to insist upon
every person in the Post Office taking the sacrament,
so called; at which I was not surprised; for in my hearing,
one of the Postmasters-general in a violent passion, and swearing vehemently,
asked if there were any more men who thought as I did; declaring if there were,
they should all turn out.
Endeavours were used to make me appear criminal and worthy the treatment I received;
and to give the greater appearance of justice to their proceedings,
they reported that the judge at the Assizes had said in open court,
that I was a man very unfit for any employment in the Post Office,
and that he intended informing the Postmasters-general as much;
which was altogether untrue, nothing of the sort having transpired; but on the contrary,
the judge behaved with much tenderness and feeling towards me.

Seeing how involved in difficulties we were,
my opening this matter to my wife was a severe trial to me;
and none but the Almighty could conceive the inward distress
I suffered on being brought into this humiliating situation.
I had now scarcely a friend to whom I could open my mind;
and my father and other relations treated me with coldness, especially the former,
who declared he would never do anything for me.
None offered me any assistance, and I dared not open my situation to Friends,
lest they should suppose I courted the Society for gain.
My wife too,
(who was violently opposed to Friends,) perhaps with a view
of forcing me to return to my former way of thinking,
appeared uncommonly bitter against me; so much so,
that in the hurry of her resentment she left the house, with the determination,
as she said, never to return, and took the children with her.
I entreated her before she left, not to prosecute her intention;
nor did I expect she would, till she put it in execution.
She was at a relative`'s at Richmond for some time;
and while she was there I wrote to her in as moving a manner as I was capable,
to request her to return.
She came afterwards to get clothes for herself and the children,
when I renewed my entreaties with many tears, but in vain.
In this season of distress, the love of God through Christ was my only comfort,
and in this I felt experimentally that I was not forsaken
by Him for whom I suffered such severe trials and conflicts.
Under the pressure of them I wrote as follows:--

[.embedded-content-document.paper]
--

My brethren are put far from me, and my acquaintance are verily estranged from me.
My kinsfolk have failed, and my familiar friends have forgotten me.
They that dwell in mine house count me for a stranger; I am an alien in their sight.
My breath is strange to my wife,
though I entreated for the children`'s sake of my own body.
All my friends`' abhorred me; and they whom I loved are turned against me.
Lover and friend you have put far from me, and my acquaintance into darkness.
But I know that my Redeemer lives,
and that he shall stand at the latter day upon the earth.

--

After an absence of several weeks my wife returned to me; and I can truly say,
I received her joyfully.
During the time of these deep probations,
I was also under great discouragement respecting my outward affairs.
When I had been in business about a year,
on making up my accounts I found my debts exceeded my property by upwards of £1000;
and the next year there appeared but little improvement;
for in these two years my business did not clear my expenses by about £300 a year.

In the beginning of the year 1785, I was kindly noticed by a few Friends,
whose society I very much enjoyed, home being generally very unpleasant to me.
In the First Month of this year George Dillwyn and Samuel Emlen,
who were visiting the families of Friends of Westminster Meeting,
expressed an inclination to sit with me;
and I met them for that purpose at George Stacey`'s.
I felt in an unusually disconsolate state,
and unable to see anything but the impurity of my heart.
The subject of their testimony was to encourage faithfulness
in little acts of dedication that were required of me;
intimating I was not to suppose that, because I had suffered for the cause of truth,
the work was done; that there was still a great deal to do, and perhaps to suffer;
and that it is only by patience and watchfulness,
and keeping the eye single to the great Master, that we can be safe;
that seeing we are weak and insufficient of ourselves to do anything to His glory,
we must seek for ability to serve Him with a perfect heart and with a willing mind,
that by the purity of our conduct we may prove ourselves
worthy of the calling with which we are called.
The upright, honest dealing of these Friends,
was a stimulus to me to press through every difficulty and discouragement.

The adoption of the plain language was a great trial to me,
and it was a long time before I could fully give up to it;
and even after I had accomplished it, and had continued faithful for some weeks,
my strength failed me, and I nearly gave it up:
but by attending to the secret reproofs of instruction,
I was favoured with strength to resume this part of my duty;
though I found it much more difficult to return,
than it was in the first instance to conform to the practice.
Thus by unwatchfulness,
and not attending to the pointings of duty in what appeared little things,
I was frequently brought into much distress; but when faithful to the voice of Truth,
I was at times favoured with great peace and comfort,
and found I gained strength in the holy warfare.
Though neither dress nor address at first appeared of much importance to me,
yet as I faithfully yielded to the teaching influences of Divine grace and truth,
I was enabled to see the beneficial effects of supporting these parts of our testimony.
When I first altered my dress, the tailor, contrary to my directions,
made my coat with a cape and cross pockets.
The cape I had altered,
but as the alteration of the pockets would have disfigured the coat, I retained them,
though it cost me considerable uneasiness.
By this little exercise I was put to the test, whether my alteration was from principle,
or merely an act of conformity to the customs of Friends,
which I have always thought a matter of no small importance:
for to get into the fold by any other way than by the door,
or following any other leader than the true Shepherd, I believe is unsafe;
and however desirable it may be to conform to the views and practices of our brethren,
this is not sufficient to build a religious scruple upon.

My natural disposition was volatile and lively;
at the same time I was hasty and impatient of contradiction.
I scarcely seemed able at times to keep my vivacity within due bounds,
which was often a great trouble to me.
I therefore abstained from animal food, etc., thinking that by mortifying the body,
I should be able to conquer this enemy to my peace,
as well as others by which I was assailed.
This voluntary abstinence caused me much distress;
being unable to give a substantial reason when I
was questioned upon the subject by my wife and others.
I continued in this course for some months, till my natural strength was much reduced;
but my animal spirits were greatly increased, and I thus discovered that all human means,
not in the Divine economy, are insufficient to bring about the work of regeneration;
nothing short of the light and power of Jesus Christ
being able to effect this great and important work.
For many months I had to travel on under the pressure of outward discouragements,
so much so that there was little appearance of my getting forward in business:
though at some times the prospect was more cheering than at others.
Keen was the distress that I suffered, and many the tears that I shed.
I had also a host of enemies within, whereby I was kept in a state of continued warfare;
fearful lest I should not be able to stand my ground, and after all my sufferings,
bring reproach on the Truth.

My dear wife was all this time unable to comprehend
the meaning of the peculiarity of my conduct,
by which we had been brought into these circumstances of difficulty;
and not being reconciled thereto, she frequently upbraided me.
This was a cause of great disquiet to us both;
and it is likely my yielding to the natural warmth of my temper,
made my own path considerably more trying than it would have been,
had I borne with patience the contradictions I met with.
I did indeed strive to get the better of this evil; and Oh,
the distress and agony which I have sometimes felt, when under the influence of it!
My wife, who formerly was all mildness and meekness, was now an altered woman,
having become severe, contentious and vindictive, displeased with everything I did,
and indisposed to please me:
and thus we were at this time completely alienated from each other.
But alas!
I ought to have shown a greater degree of condescension,
and to have been more like the Master, who when he was reviled, reviled not again.

On account of my wife`'s forbidding and distant behaviour towards Friends,
I seldom had any to call on me, which I thought hard.
Sometimes, indeed, they pressed through all; and, as they kept their places,
their visits generally ended well.
It happened once that Timothy Bevington and John Burlingham
of Worcester were on business in the neighbourhood;
and though unacquainted with me, they agreed to call on me,
and accepted an invitation to dinner.
After dinner, with much difficulty, on account of my wife`'s objection to stillness,
a religious opportunity was obtained;
wherein Timothy Bevington gave us some excellent advice,
and at the same time told me he had an assurance that if I kept my place,
my wife would be given to me; an occurrence I could at that time have no prospect of,
nor had I faith to believe it.

I had been a constant attender of meetings;
and sometimes when I had occasion to go into the city,
I took the opportunity of attending one of the meetings there.
One day, having business in the city, I intended to go to the meeting in White Hart Court.
In passing along Holborn I saw a poor woman apparently in great misery and distress,
the effects, perhaps, of a life of dissipation.
I felt an involuntary sympathy for the poor creature, but passed on.
She, however, took such hold of me, that my mind became agitated,
and I was for a time withheld, as it were, from going any farther.
I accordingly stopped and endeavoured to compose my mind,
having never felt anything of the sort before.
I soon had an evident impression to go back, attended with these words,
"`obedience is better than sacrifice.`"
I continued for some time undetermined what to do.
Time seemed to call for some conclusion, lest I should be too late for meeting.
I could not, however, give up to go back; many weak reasons coming in the way;
I therefore proceeded under a full conviction of disobedience.
After I had been seated in meeting for some time, my mind became tranquil;
and I felt sufficient life in me to pray for strength and a willing heart,
whenever the Lord might be pleased again to call me into service.
In the midst of my cogitations,
George Dillwyn in a singular manner pointed out the consequences
of a neglect of duty when it became clearly shown to us,
which he said was the case, he believed, with a state then present; who,
though they had known a being led into the wilderness,
if a repetition of disobedience were to take place,
must not be surprised if they experienced a continuing
much longer there than the Master ever intended;
and admonished those present to beware of this, and press forward to the mark, etc.
I was much humbled at this testimony, seeing that I could not hide myself in a corner.
Surely it is a glorious privilege to be led out of the labyrinth of self-will,
by the hand of the mighty God of Jacob.
These circumstances made a deep impression on my mind, and I trembled at disobedience.

About this time I had an extraordinary dream,
which I could not at first well understand the meaning of;
the natural man could not comprehend it,
though afterwards I was made sensible that it was of no common interpretation.

I thought I was alone upon an open heath or common,
where it thundered and lightened very much;
the atmosphere appeared illuminated with the dreadful
flashes that seemed to surround me on all sides;
there appeared no way for me to escape.
I thought every moment, the next flash would destroy me.
In the midst of my distress I observed that the lightning
had set fire to a town at some distance from me,
and as near as I could judge, destroyed about a third of it.
I now expected my dissolution was near,
but I was much surprised and consoled by hearing a voice from above,
directed to myself to this purpose, "`Fear not, but be faithful,
and none of these things shall happen unto you; but unto every town,
and even village in this kingdom, thus shall it be.`"
I soon awoke under an awful sense of the merciful preservation I thought I had experienced,
and an extraordinary dread was upon my mind for some time afterwards.
At first I was ready to conclude that this country
would be visited with some dreadful calamity,
but afterwards I was led to believe it concerned myself alone,
and that faithfulness would be my preservation under the many trials
and difficulties which seemed to surround me.

Although I was so much oppressed as above represented,
yet there were seasons of sweet enjoyment permitted me,
wherein my cup might be said to run over:
for days and nights together I have been almost lost in the excess of heavenly love,
and +++[+++at times]
dared not stir lest it should be removed from me.
Thus was I led on through various dispensations;
during which I could not but admire and adore the gracious
Hand that was thus mercifully conducting me.

About the year 1786,
several things occurred which evidenced the care of the Good Shepherd towards me,
a poor worm.
He, in mercy, saw fit to disclose himself to me,
and by the might of his own power manifested that he was
able of the stones to raise up children unto Abraham,
if I did not reject so great salvation.
I had still great difficulties to struggle with,
and had none to look to for help but the blessed Redeemer; the Lord alone was my support.
The difficulties we were under produced great humiliation:
the creature of necessity was to be reduced:
not a stone of the former building was to remain; all was to be razed,
that the wise Master-Builder might erect his temple in the heart,
Jesus Christ`' being the chief-corner-stone.

[.offset]
+++[+++The writer,
after stating that himself and wife had in their
prosperity enjoyed many outward comforts;
that now in their reduced condition,
duty and necessity combined to induce them to make sacrifices
which by some would have been considered costly;
and that among other things, a sideboard of plate was disposed of, proceeds:--]

To be thus reduced was no small trial to flesh and blood, but the plate was called for,
and it was given up.
In our straitened circumstances it would have been folly to purchase it;
and now possessing comparatively nothing,
vanity alone could be the inducement for keeping it.

This year my business increased: on taking stock,
I found I had just about enough to pay all my creditors twenty shillings in the pound.
Such being the case,
I thought I would not again run the hazard of causing any person to lose by me,
unless with his own consent.
I therefore, upon mature deliberation,
came to the humiliating conclusion to call my principal creditors together,
in order to acquaint them with the exact state of my affairs,
and to offer to give up my property to them if they chose to accept it;
but that if they were willing to let me go on in business,
I intended to avail myself of their kindness.

One day while at dinner, pondering this subject in my mind,
and bewailing the trying circumstances to which I was reduced,
I was so overcome by my feelings that I burst into tears,
(my family being all around me) and mentally poured out my soul to my Heavenly Father.
While in this humble situation of mind, a letter, per post, was delivered to me:
it was from a person of property who had married a relative of my wife`'s,
and was to this effect:

[.embedded-content-document.letter]
--

[.salutation]
Sir,

I have made my will and have left your wife £+++___+++;
but believing it may be of more use to you now, than it may be at my death,
you are at liberty to draw upon me at sight.
I am, Sir, your humble servant, etc.

--

The person lived at Newcastle-upon-Tyne; his wife was dead.
I had never seen him nor corresponded with him,
and my wife had only seen him when she was a child;
so that we could have no expectation of any such communication from him.
This sum was sufficient to enable me to carry on my business without risk to my creditors;
and my poor, tried soul was bowed in humble gratitude +++[+++to my Heavenly Father],
for having thus manifested his lovingkindness towards me,
and confirmed the everlasting truth, that "`for the oppression of the poor,
for the sighing of the needy, he would arise.`"
Surely this was a memorable token of his fatherly care over his children.
I was sensible that there was none in heaven but Him, nor in all the earth,
that I could depend upon but Him; to Him alone I wished to render all the praise.

The time now came that Friends began to look towards my being received into membership;
and I understood afterwards, that some difficulty had arisen,
on account of my not having applied to the Monthly Meeting for admission.
This was, however, soon got over, as in the course of conversation with some Friends,
the question was put to me,
whether I had ever looked towards the Society with
a desire to be more nearly united to it?
I very readily answered in the affirmative, adding,
that I did not feel the same anxiety respecting it that I once did,
being willing to wait the Lord`'s time in this,
as well as in every other occurrence of my life;
and left it entirely to them to mention it to the meeting.
I was soon after this visited, by appointment of the Monthly Meeting, by a committee of,
I believe, judicious Friends,
who were not willing to take things by outward appearance only;
for I believe I thought quite highly enough of myself,
and supposed I had made considerable progress in religious experience.
But the first visit convinced me of my error;
and I was much humbled under a sense of my own emptiness and lack of all things.
I remained much exercised till the Friends had another opportunity with me;
when to myself I appeared much darker than before, and according to my own feelings,
in no situation to be received into membership.
I was also much deserted, and tried with many close inward conflicts;
and as the Friends gave me little or no encouragement,
I apprehended I was now entirely lost, being, as I thought,
shut out from the blessed unity of the Spirit, both with the Almighty,
and my beloved friends.
Great was my distress and searching of heart at this season of deep humiliation;
here self was in no estimation.
I often thought the pain and exercise I had to pass
through was more than I could well bear for a continuance,
and seriously feared the effects of my present trouble.
In the midst of this close trial, on the Sixth-day previous to the Yearly Meeting,
I was informed by a Friend that the Monthly Meeting had acknowledged me as a member,
and that I was therefore at liberty to attend the Yearly Meeting.
I cannot express the joy I felt, and the favour I considered it,
to be united to that body with whom I had so long felt a union;
and great were my cries that I might know preservation from evil,
and not be permitted to bring reproach on the ever-blessed Truth.
I have often, on looking back,
had to admire the goodness of the Almighty to my poor soul,
in suffering this dispensation,
and that I was not admitted into the Society in a superficial manner,
nor made to think myself better than I was;
but that wise and feeling brethren were sent to examine
and feel for themselves and the meeting.

A circumstance occurred during the Yearly Meeting,
which led me to consider the nature of appointments to services in the church,
and the manner of their being made.
The nomination of Friends to their rightly allotted services,
has appeared to me to be a matter of great importance;
and that those who nominate should do it under a feeling of its propriety,
rather than from the apparent qualification or ability of the individual,
or a partiality for him; remembering that He who alone can rightly qualify,
often sees fit to dispense the gift to the meanest instrument,
that thereby his name may be more eminently glorified:
and that unless we wait upon him for a right influence,
his work may be marred in our hands, as I fear is often the case,
by the officiousness of forward and unskilful spirits,
who are more earnest to maintain an authority in the church,
than to submit to be led by Him, whose ways are in the deeps.
The hasty refusal of Friends to accept appointments,
when perhaps the nomination has arisen from a weighty
impression as to the fitness of the individual named,
has appeared of equal importance.
Some refuse through diffidence; others,
from not having felt anything towards the service;
and too many from an unwillingness to give up their time for the service of Truth,
the things of this world standing too much in the way.
To the diffident I would say, that they should recollect, the work,
if rightly entered into, is not theirs but the Master`'s, "`who puts forth his own,
and goes before them.`"
The same may be said to those who have felt nothing
towards the service to which they are nominated;
and that if they do not feel anything against the appointment, it is better to accept it,
because by going blindfold to the work,
with their dependence wholly on the Good Shepherd for help and guidance,
they will probably be enabled to do it more to his honour,
than if they had a clear sight beforehand.
As to those who grudge the time that the Master`'s business requires,
the little experience I have had has shown me,
that such as these have almost imperceptibly dwindled to nothing,
as to the substantial part of religion, and have degenerated to mere lifeless formalists;
according as it was said of those who lusted after
things that were not convenient for them;
"`He gave them their desire, but sent leanness into their souls.`"

Although my dear wife and myself were not yet so united as I could have wished,
yet there appeared some ground gained.
I have already stated that Timothy Bevington, in a religious opportunity,
spoke encouragingly to us.
Some months afterwards, on meeting him again,
he told me he recollected what had come before his mind at that time;
and though what he had said was not yet realized,
he notwithstanding had a renewed belief that "`my wife would be given to me.`"
I had been very cautious at all times of saying anything
by way of persuasion as to my wife`'s religious movements,
except that I sometimes urged her to the attendance of her own place of worship.
Indeed, I was satisfied that it would answer little purpose,
unless I could feel myself warranted to press anything
on her from the influence of Divine love,
which I thought I might at some time be favoured to feel.
Her health was often very indifferent; the air of London did not suit her,
so that we had, for a considerable time,
been under the necessity of having a lodging out of town,
where she frequently remained for several days together when she was unwell.
This was the case near the latter end of this year, and I was left in town.

One day, while serving a customer in the shop,
I felt the sweet influence of heavenly love in a remarkable degree, and at the same time,
such a powerful union with my dear wife, that I was overcome with the sensation:
and having dismissed the customer as speedily as I could,
I went upstairs to give vent to my feelings,
where I continued the greater part of the day.
Under this influence I felt an inclination either to speak or write to her,
on the subject of a nearer religious fellowship.
I was not, however, in haste to put it in practice, but waited till the next day,
that I might, when my mind became more settled, judge of the propriety of such a step.

The next day, on sitting down before Him by whom I wished to be rightly instructed,
I again felt the same sweet impression; when, without hesitation,
I wrote a few lines to her, expressive of what I felt.
I took the letter that evening, and soon found that the Master had been there before me.
She read what I had written several times over, but said nothing.
After a time, I ventured to begin the conversation, though in much fear and brokenness,
and I told her all that I had felt.
She was much affected at the relation,
and asked me at what time of the preceding day it was,
that I felt the impression I spoke of; I replied,
that the clock struck eleven as I was going upstairs, on leaving the shop.
She said it was very remarkable,
for just at that time she felt the same impression towards me,
which had continued with her ever since, much to her comfort and consolation.
We now mingled our tears of real joy together, under a sense of the gracious dealings,
of our Heavenly Father to our poor souls;
and we had to admire that our present union had not been effected by any human means,
but by the power of the Lord alone, He having given my wife to me.
Great, I believe,
were our desires that we might in no respect know a separation from each other,
but that we might so walk before Him as to experience
a continuance of his love and regard.
I believe we both considered this extraordinary manifestation of Divine love,
through which we were so sweetly united, as our spiritual marriage;
for what we had before known of love,
fell far short of that which we now felt towards each other--no,
appeared as nothing in comparison of it.
This, I apprehend, is what all ought to feel on entering into this solemn engagement.

My wife was at this time very much indisposed, and had to endure a great deal of pain,
so that she was often ready to cry out from the agony she suffered;
but she was at the same time, under a very precious visitation;
for in the midst of her suffering she felt such a flow of Divine comfort,
as made her bodily affliction appear as nothing to her; and,
as she has frequently told me since,
she was at times ready to pray for a return of her pains,
in the hope of being favoured with a return of heavenly love and consolation.

About this time, as she informed me several years afterwards, she had a singular dream,
which, as it conveys instruction, I shall here relate.--

She thought that as she and her brother were walking together,
they came to a large flight of stairs, which she ventured to ascend,
but left her brother at the bottom.
When she had reached the top, she saw two angels in white raiment, each having a trumpet,
which they placed to their mouth, and said with loud voices, "`Repent,
for the kingdom of heaven is at hand.`"
They then led her forward amidst an innumerable company of angels,
where the sweet sensation she felt was beyond description.
They afterwards brought her back again and down the stairs.
She wished to return with them, but they pointed to two roads;
the one on the left hand was a large open and beautiful plain,
that on the right a rugged and narrow path.
She was told she had her choice which way to go, but if she intended to come there again,
it must be by going along the rugged and narrow way.
They then left her, and she soon afterwards awoke.
The next First-day, she went to her usual place of worship,
when the minister took for his text the words, "`Repent,
for the kingdom of heaven is at hand.`"
This brought her dream afresh to her remembrance,
and it seemed to have the effect of making her more
earnest to know which way it was her duty to go.
After a time, she found most peace in going with me.
I left her entirely to herself as to her attending Friends`' meetings,
being satisfied that He who had visited our souls in so extraordinary a manner,
would in the right time, carry on the work he had begun in her.
In a few weeks after she had got better, she gradually left her former place of worship,
and we soon had the satisfaction of experiencing
"`the unity of the Spirit in the bond of peace.`"
It was no small alleviation of my troubles to have the help of my dear wife;
the union of her spirit was a great comfort to me.
She kept her place, I have often thought, far beyond myself,
and afterwards became a steady and useful member of the Society of Friends.

My business was now gradually increasing,
and I had a good hope that I should not continue to suffer the
severe discipline which I had experienced on account of trade;
a prospect appeared of my getting out of some of
the difficulties I had been struggling against.
For these and many other blessings, my heart was often bowed in reverence to God.
My trials had the effect of enabling me, from experience,
to sympathize with the afflicted.
With my mind thus tenderly exercised on behalf of a near relation,
(the daughter of an uncle,
a clergyman,) with whom I had formerly been on terms of great friendship,
I wrote the following letter to her:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Haymarket, Ninth Month 4th, 1786.

[.salutation]
Dear Cousin,

With that tenderness and sympathy, which I can with truth say,
I often feel for the afflictions of my fellow creatures,
and which at this time I sensibly feel for you,
do I now sit down to offer my mite of love towards you.
Believe me,
the account of your dear husband`'s decease gave me much heartfelt uneasiness,
well knowing the afflictive dispensation now laid upon you,
must cause sensations which cannot be easily described.
But trials of this kind, my dear cousin, we must all submit to; no,
we must not even murmur at them.
It is the Lord`'s will, and who can controvert it?
Our giving way to grief will in no way answer any good purpose,
but may perhaps encourage a melancholy which it is our duty to avoid.
We should endeavour to say in sincerity, "`Not my will, but yours be done, O Lord.`"

It has pleased the Almighty oftentimes to bring me low; and I have observed,
that in seasons of distress, my soul has been brought nearer to him;
thus I have been enabled to cry mightily unto him,
and I have ever found him a present Helper in all my afflictions.
Therefore, my dear cousin,
I would have you consider that the Lord is never
nearer than in seasons of trial and deep probation.
At these times, we feel our souls drawn towards him,
knowing our own inability to help ourselves,
with the anxious hope that he will not utterly cast us from his presence.
Trials and afflictions are sometimes as needful for the mind, as food for the body.
I have often thought, yes, I have experienced it, that a religious growth,
and a true knowledge of God,
has been more fully known by patience and resignation
to his blessed will in time of deep suffering.
When we are thus willingly led, we find him to be the Physician of great price,
the Healer of our wounds and the hope of our salvation.
But alas! there are few that can truly say, "`a Saviour or I die,
a Redeemer or I perish`" And what is the reason We are not
willing to undergo the refining operation of his hand.
"`As gold is tried in the fire, so are acceptable men in the furnace of affliction.`"
Those whom the Lord loves he chastens;
therefore let us keep in his love by submission to his will.
"`Woe unto them who have lost patience! for what will they do when the Lord comes.`"

Happy will you be, my dear cousin, if you look to him alone for help;
then he will never desert you; but the more you cast your care on him,
the more he will manifest himself unto you.
Think not your present affliction is more than you can bear.
Remember David`'s resignation and faith; and if you take his example,
you will in your distress, have to say as he did, "`Why are you cast down,
O my soul and why are you disquieted within me?
Hope in God, for I shall yet praise him, who is the health of my countenance and my God.`"
Humble yourself before him,
and I have not a doubt but that you will yet have occasion to rejoice.

I think I have little more to add, than if I can in any respect assist you,
my dear cousin, I shall be happy to do so;
therefore do not let a fear of giving trouble be a motive for not +++[+++asking my aid.]
I therefore conclude,
sincerely desiring that the Almighty may look with
tenderness and compassionate regard upon you,
and that you may be preserved in his love in this season of severe distress.

[.signed-section-closing]
Your affectionate cousin,

[.signed-section-signature]
Frederick Smith.

--

The path which I had to tread seemed different from
that into which many others had been introduced;
but it was one, to the trials whereof, after struggling for a time,
I was generally obliged to submit:
this led me to feel for other fellow travellers in the strait and narrow way,
whose exercises were different from those of many
who had obtained their religion by education.
In some of the Meetings for Discipline which I attended, I was brought very low,
by observing the off-hand way in which some who had not been baptized through suffering,
conducted the affairs of the church; and I also had silently to mourn over those who,
as delinquents, had become the objects of the discipline;
having often to look back at my own state,
when in bondage and captivity in the days of my youth;
the recollection of which I considered as a great favour,
being thus preserved from thinking too highly of myself, or from a disposition to say,
"`I am holier than thou.`"
The narrow path into which I was led,
occasioned Friends to exercise a tender care over me;
those of more experience than myself, watched over me for good,
lest the enemy might deceive me by some of his transformations,
which he usually attempts in the early days of the espousals of the Lord`'s children.
The goodness of the Lord is great; and sometimes his visitations are marvellous,
beyond the comprehension of man.
Such has been his condescension, that I have been instructed in the night season,
at times when I have been ready to faint, and when human help seemed unavailable.
How shall I recount his lovingkindness during the travail of my soul!

I suffered sore conflict from a fear of having mistaken an apprehended duty;
more especially as some of my friends had queried with me,
whether this had not been the case; for though I could not see that I was in error,
yet I was not certain that it was not so.
While in this situation, my mind was much tossed, and I had the following dream:--

I thought I was with some Friends with whom I was particularly intimate.
They were viewing a newly-erected building which seemed to them to need a little repair;
and just as I was about to give an opinion,
I was secretly told I had nothing to do with that matter,
my business was to keep the righthand road; and upon looking about,
I observed there were two roads before me, the one on the left seemed broad and pleasant,
that on the right was very narrow and rugged, which latter I took.
It was with some difficulty I could get along; but after labouring for some time,
I got to the end of this narrow way, and came to a pleasant green field.
As soon as I entered this open space,
my mind was so overcome with the enjoyment of Divine love,
that I burst into a flood of tears.
O! the love I felt to the Almighty, is beyond expression.
I inquired the name of the place where I was, and was answered, "`It is Heaven.`"
I remained under this sweet impression of heavenly enjoyment for a considerable time;
and when I awoke, I continued praising God for his goodness to my soul,
the rest of the night.
I was instructed to believe, that the newly-erected house,
which my friends apprehended needed a little help, was myself, but that I was to hear,
and not contend; that I was steadily to follow my Guide,
and he would lead me into the right path, and my reward should be sure.

I apprehended there were few who had to endure greater conflicts than myself;
yet there were times wherein my gracious Master was
pleased to favour me with his life-giving presence;
and although I was still in my infancy as to religion,
I could discern the states of others: but I kept these things much to myself.
As Mary did,
"`I pondered these things in my heart,`" thinking
it not right to disclose the King`'s secrets.
I thought it was not improbable, that at some time I should be called to the ministry;
having at seasons to wade as through the rubbish.
This the exercised traveller is not unfrequently obliged to do,
before he can reap the reward of his labours.
I was at times, ready to cry out to those who were standing in the way,
and were not only idle themselves,
but hindered those who were anxious to do the Master`'s work.
I was not, however, hasty in this matter, the time not being fully come.
I believe I sometimes heard the Shepherd`'s voice,
although like Samuel I did not then fully know from where it proceeded.

Among the occasions of my spiritual conflict, was a temptation to infidelity;
this sore trial was altogether sudden and unexpected.
I was one day looking over a Review, and read a short sentence,
which was an extract from the work of a deistical writer.
It was like an arrow which made a deep wound in a vital part.
I instantly became beclouded with doubts, and so distressed that I knew not what to do.
I thought all I had been building up was in vain,
and that there was no certainty as to the christian principle.
I felt it was an attempt of the enemy to ensnare me,
and was permitted for a season to doubt.
I dared not open my mind to anyone on the subject,
lest it should be suspected that I was not sound in the faith.
Thus I was brought to a full dependence on the Lord alone for help,
believing that he only could cure the wound which had thus been received.
I endeavoured to keep my mind as quiet and easy as I could,
trusting that the mystery would, in the right time, be unfolded.
I was six weeks under this exercise: great were my cries to the alone Helper,
and he heard me.
Being at a meeting at Hammersmith, the Master saw fit to open my understanding,
so that those things which had disturbed my peace, became clear and beyond all doubt;
and towards the close of the meeting, I had an evidence given me,
that what was now opened to my view,
was not exclusively for my own individual instruction;
but that there was a state then present, who had drank large draughts of infidelity.
I had not, however, strength to open my mouth in the meeting.
Towards the close, a Friend expressed somewhat in the line I had been exercised in,
which in some degree relieved me.
On my return to London with a Friend, I mentioned the apprehension I had,
respecting the state above-mentioned; he informed me I was right,
there having been a Unitarian preacher present during the whole of the meeting.

The close of the year 1788 was a time of great exercise to my mind;
and I experienced the buffetings of Satan in various ways.
I was, notwithstanding, desirous under all,
to attend to the secret instructions of my holy Leader; and great were my cries,
that I might not be permitted to fall, or be led into error;
so that my attention seemed much fixed, even as to my outward movements,
to know his voice.
One First-day morning, I had an impression,
although so gentle as scarcely to be perceived,
that it would be right for me to go to Hammersmith Meeting,
which began at eleven o`'clock.
I could hardly come to a determination, when the clock struck ten.
There was now no time to spare, the distance to Hammersmith being five miles;
so I even concluded to go there, and walked very fast.
When I came to the wall beyond Knightsbridge, a man joined me,
and walked beside me without saying a word: we both turned in to the meetinghouse.
It was a precious meeting, and when it concluded,
I hastened back and attended Westminster Meeting, which began at two o`'clock.
On my return, the same man joined me again;
and all the conversation that passed between us was--I asked him,
"`Whether he had been among the Methodists`" to which he replied, "`Yes.`"
We walked on together for some distance, but he could not keep up with me.
Some weeks after this, I observed him come into Westminster Meeting,
and sit down very solidly.
He came again in the afternoon,
and continued to attend meetings on First-days for some weeks;
after which I told him we met on Fifth-day mornings also;
whereupon he became a regular attender of our mid-week meetings.
After a time, I took some further notice of him; and he once told me,
that having become much dissatisfied with continuing with the Methodists, he had,
on the day we walked together to Hammersmith,
gone out with a view of observing which way Providence would lead him,
and whichever way that should +++[+++appear to be], he meant to try it;
and if he could be easy therein, to follow it: that seeing me walking very fast,
he concluded I was going to some meeting, and he determined to follow me:
that he felt so much peace while in meeting,
that he believed it would be right for him to give up to attend our meetings,
which he could not at first do.
But when he saw me, (as, being resident in my neighbourhood,
he often did,) his conscience struck him for his cowardice;
and at last he was obliged to come and sit with us.
He was a solid man, and was afterwards received as a member among us.
I record this,
to show the necessity of ever attending to the tender feelings of the mind,
and of taking care not to throw them hastily by, without giving them due consideration.

[.small-break]
'''

Although the following account may not be considered as a part of my Memoirs,
yet as it has afforded me instruction, I shall here narrate it:

[.small-break]
'''

J+++.+++ C. was a person, who in the early part of his life resided at Bristol,
but afterwards near London.
He had been disunited from the Society of Friends for several years,
but occasionally attended Friends`' meetings.
For a year or two past, he had become attached to myself and family,
though on the whole not much so to Friends as a Society.
He was at this time more than ninety years of age.
One evening he came to drink tea with us, and in conversation,
alluding to a young man who was of our company, he said,
"`I remember the time when I was as plain a Friend as he is;`" and went on to inform us,
that when he was a youth, though his parents were gay,
and very little of Friends in appearance or otherwise,
yet himself was seriously inclined, regularly attended our religious meetings,
was particular in his attention to the plain language, also in his dress,
and in keeping his father`'s books according to the practice of Friends,
as to the names of the days and months.
When he was about twenty-one years of age, as he was sitting very solidly in meeting,
and under a close exercise of mind,
he apprehended himself called upon to say a few words in the line of the ministry,
which through weakness and fear he neglected to do.
He had the same impression on his mind at several meetings afterwards,
to which he uniformly neglected to attend;
and at last determined never to expose himself in that way.
The frequency of this impression,
and the distress of his mind on account of his refusal to attend to it,
at last had a sensible effect on his bodily health; which being observed by his father,
he requested a physician who was intimate with the family,
to find out what his complaint was, and to prescribe for him.
This he attempted; but finding medicine to be of no use,
he told his father he believed his complaint was out of its reach,
and that he apprehended his disease was on the mind; adding,
that if he could discover the occasion of his distress,
it might lead to a means of relief.
Accordingly his father, in a very affectionate manner,
told him what his apprehensions were; and withal, that as he knew he tenderly loved him,
if he would let him know the cause of the melancholy which seemed to oppress him,
he might depend on his doing all in his power, as a parent, to make him happy.
After urging him for some time,
he confessed that it arose from disobedience to revealed duty, as above related;
and that now all power to do the Divine will was taken away,
so that his life was become miserable.
His father urged him to comply with the holy requisition;
but he told him it was now too late, he had done violence to his best feelings,
and that he should never have a visitation of the like kind any more.
His father again consulted the physician,
who advised him to send his son to some distance from his friends,
which was speedily done;
and his father gave him the superintendence and management of some mines in Wales.
Here the tendering impressions of religion were soon lost; and instead of them,
he had a settled gloom and continued distress of mind,
so that many times he feared his senses would become affected.
He said he remained for twenty years together in this state truly afflicted;
and though at the end of this time he seemed to get over these unhappy feelings,
yet they frequently returned for years together, during his long life.
He added, that possessing a good understanding,
he had a turn for mineralogy and chemistry;
and was considered superior to most in his day,
having made many improvements in these sciences;
and that other persons had richly reaped of the fruit of his labours,
but that everything, as to himself, had failed of success.
A blast had overtaken all his endeavours;
and though never extravagant in his own expenses, he became reduced in his circumstances,
and was now literally living on the bounty of others.
He was taken ill when nearly a hundred years old,
and during his illness showed no marks of religious sensibility.

[.small-break]
'''

In the year 1789, I was tried various ways: I was much tempted,
experienced much spiritual desertion,
and felt keen distress for the loss of the beloved of my soul:
but there was an Arm underneath which supported,
and under every temptation a way was made for my escape: adorable condescension.
Every token of friendship,
every act of kindness from my brethren appeared to be more than I deserved.
I became in my own view, as the off-scouring of the earth.
During these close exercises and deep baptisms, my soul was exceedingly sorrowful,
even unto death, and I had no idea of what was to follow them.
He who knows how to prepare and qualify his servants, is pleased to do it in his own way;
not according to the weak apprehension of his creature man.
He causes his children experimentally to know,
that his strength is made perfect in weakness,
and that his grace is sufficient for them.

Very early one First-day morning,
I felt an impression that I must go to Ratcliffe Meeting.
I would have put it by, and endeavoured to reason it away;
but I was at last obliged to submit.
Soon after I got there, very unexpectedly,
John Pemberton and James Thornton came into the meeting.
About an hour after the meeting was gathered, I felt an uncommon exercise,
and afterwards a secret impulse to engage in vocal supplication.
O, the awful distress which I felt!
I was naturally averse to speaking in public,
often experiencing it to be a great difficulty in our own Monthly Meeting.
After waiting a considerable time in great conflict of spirit,
apprehending myself so abundantly weak,
and every way unworthy and unqualified for so important an undertaking,
I allowed the meeting to break up, without performing what appeared to be my duty.
Great was my distress and agony for this act of disobedience,
even such as is not to be described.
The two Friends above-named asked me to go with them
to the Friend`'s house where they were to dine,
which I did; and dear John Pemberton, perceiving all was not right, asked me the reason,
which I was not easy to inform him, and put it by.
I thought notwithstanding, if ever I should be thus called on again,
I would endeavour not to refuse, and in the afternoon,
waited to feel an impulse of the same kind; but the Lord`'s time is not our time.
After the meeting was over,
I went with John Pemberton and James Thornton to a Friend`'s house at Bromley;
and after tea, in a religious opportunity there, I felt the exercise and the command;
and after much severe conflict, I gave up to express a few words in supplication.
After the agitation was over, I became still and quiet,
and humbly thankful that the Lord in mercy had accepted
this small sacrifice from a rebellious heart.
My kind friends John Pemberton and James Thornton expressed their unity with me,
and comforted me under my present exercise, as we walked from the Friend`'s house.
I returned home sweetly rejoicing,
having seen of the long travail of my soul and become satisfied.
This was on the 28th of the Sixth Month, 1789,
the day on which I was thirty-two years of age.
Those only who have entered into this service from the necessity alone,
after having been made willing through suffering to become anything or nothing,
can form any true judgment of its awfulness; at least it so appeared to me,
under the varied baptisms I had been plunged into,
in order to be prepared for this engagement.
To a diffident mind, and one who had at times experienced much Divine favour,
it was a sore trial thus to expose myself,
and become a preacher of righteousness to others.
I was humbled as in the dust, and tears were my food day and night for a season.

At our Quarterly Meeting in the Ninth Month, I became much exercised,
and in the early part of the meeting,
I felt it to be my duty to open my mouth in supplication; but I endeavoured to put it by,
till near the time for breaking up the meeting, when I fell on my knees,
and stammered out a few words.
Although this produced peace to my own mind, as the result of giving up to apparent duty,
yet I have since thought, with respect to such cases, where weakness has thus got in,
and the right time for offering the sacrifice has passed by,
it might be profitable to consider, whether it is not better to bear our own burden,
rather than to offer unseasonably in a solid meeting; yet this is a weighty matter,
and ought not hastily to be decided on.
It must be confessed, that when the true order is maintained,
and every one moves in his proper place, the regular line of the ministry is beautiful,
the harmony of the gospel is preciously felt, and the Lord is glorified.
It is likely my beloved friend James Thornton apprehended I had let in some discouragement,
and therefore, in order to reconcile me to my apparent hard service,
he told me he had good unity with me therein, and especially on that day;
and with other weighty and truly fatherly counsel,
he told me I must not expect a smooth path; adding,
"`I believe you will have many instructors, but few fathers,
so be prepared like a valiant soldier, to endure hardness in the Lord`'s battles.`"

While John Pemberton and James Thornton were in London,
we had the satisfaction of having much of their company;
the former frequently lodged at our house.
He was a man of an affectionate and kind disposition, with great humility,
and a most benevolent mind.
I understood that in his visit to Ireland, he expended among the poor of that nation,
more than a thousand pounds.
While travelling through Scotland, he was equally liberal to the poor of that country;
and finding, in his visit to the northern islands,
that the inhabitants had nothing to eat but dried fish, when he returned into Scotland,
he loaded a vessel with meal, as a present to these poor islanders.

While at Lincoln, in company with Thomas Ross, also from America, and some other Friends,
John Pemberton had a particular wish to have a meeting
with the soldiers that were quartered there;
and application being made to some of the officers for leave, it was refused.
This produced great exercise of mind to John Pemberton, so that he could get no rest;
nor could he leave the place, much to the mortification of Thomas Ross,
who wanted to be moving forward.
At last as he was laying on the bed,
it came into his mind to make inquiry whether the
commander of the regiment was in the city.
This being done,
it was discovered that he was John Pemberton then said he would go to him himself.
When he got to the house where he was,
he sent up his name and added "`from Philadelphia.`"
The General desired Mr. Pemberton might be told to walk in.
On entering the room the General rose up to meet him,
and in the most affectionate manner asked after his health,
expressing the great satisfaction he felt at meeting with him in England,
and inquired how he had found him out.
All this much surprised John Pemberton,
and he told the General he thought he mistook him for some other person.
But the General asked him if he did not remember his being
quartered at his house during the American war,
adding, "`If you do not, sir, I do;
also the great kindness I received from you and your family.
I have every reason to be grateful to you; and now you are in England,
if there is anything in which I can contribute to your happiness,
it will afford me the greatest pleasure.`"
John Pemberton then recognized his friend, and related to him the subject of his errand,
which appeared remarkable to both of them.
He told him that if it would be any gratification
to him to have a meeting with his regiment,
it should be held in any way he should appoint,
either on the parade or in the meetinghouse; and he added,
"`both officers and men shall attend, and I shall attend also.`"
As the meetinghouse was not sufficiently large,
it was concluded to hold the meeting on the parade;
and it may be considered the most extraordinary circumstance relative to this meeting,
that the whole service, which was truly satisfactory, fell on Thomas Ross,
John Pemberton being silent.

In the early part of the year 1790 I went into Sussex,
and attended the Quarterly Meeting for that county; as also that for Norfolk,
where although I was silent I was not without exercise;
and a minister whom I did not know, told me she had good unity with me,
that though I had said nothing among them,
she was persuaded I was under much travail of spirit,
and that she believed I was much in my place in coming to that meeting.
The pressure of my exercise produced a severe fever,
so that I hastened home under great dejection of mind: I was however,
favoured to recover in a few weeks.
In the autumn of the same year I went to the Quarterly Meeting for Buckinghamshire,
and stayed a few days at Wycombe.
At this time I apprehended I was remarkably favoured
with the ownings of the Divine Master;
and one night when I went to bed,
the overflowings of heavenly goodness seemed greater than I had ever before experienced.
I became so enfeebled and wearied, that I thought my natural life would be taken away,
as I seemed unable to bear a continuance of so great a degree of heavenly enjoyment;
and I prayed earnestly that it might be taken from me,
and a portion more suited to my weak state might be given me instead:
indeed I believed great things did not become me,
and that I was unworthy of so much Divine favour.
But the next evening I became so discouraged that all seemed distress and misery;
and I never before knew a time of so much darkness and wretchedness.
I was wearied with the weight of exercise on my mind, and at length fell asleep;
but very soon felt as though the adversary fought with me, overcame me,
and pressed me down to the earth.
In this extremity I called out loudly and then awoke,
but it was only to feel the same distressing sensations and apprehensions;
and when I again fell asleep I still had to encounter them.
I got up very early in the morning in much agony of spirit, intending for London,
where George Dillwyn bore me company.
I set off under the painful apprehension that I had gone before my Guide,
and that this was the cause of my present trouble.
I ventured to open my mind to George Dillwyn,
and asked him kindly to point out to me where I had missed it at Wycombe;
but to my surprise he told me he had felt much unity and love towards me,
and that nothing uncomfortable had appeared to him;
and in truly affectionate and fatherly freedom,
counselled me against the stratagems of an unwearied enemy.

Notwithstanding the kind counsel of George Dillwyn,
I could not get above the deep plunge I had at Wycombe.
Indeed many were my trials inward and outward: the enemy pursued me on every side.
So great were my conflicts that for many months together,
I appeared as in a wilderness of thorns and briers,
where my spiritual ear was almost constantly assailed
as with noises and cries of devouring beasts of prey.
My path was as on a sea of glass mingled with fire: at every step I appeared to slide,
and to be in danger of falling into the horrible pit.
O! the dreadful season of dismay which I endured,
in order that I might know my own superlative weakness,
and that through my dear Redeemer only I could be saved.
In the midst of my troubles I was cared for many ways:
kind friends were watching over me for good.
Some of their letters conveyed deep instruction in the needful time:
I transcribe extracts from two of them as follows:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Needham, Sixth Month 28th, 1790,

I have often thought of you since I was in your company in London,
feeling great nearness towards you, and much wishing your growth and preservation;
believing if you keep your place you will have acceptable service for your God.
You must expect trying dispensations;
they are the lot and portion of the true-born children.
Trials bring us into a state of true feeling one for another; deepening our judgment,
so as to enable us to make a right distinction between thing and thing.
It is my situation frequently to be much sunk,
so afraid at times that I shall not hold out to the end, etc., etc.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
W+++.+++ C.

[.signed-section-context-close]
Philadelphia, Eighth Month, 1790.

--

[.embedded-content-document.letter]
--

[.salutation]
Beloved Friend,

On First day last in the evening, I reached my habitation from a journey into Virginia,
when I met your affectionate letter of 22nd of Second Month, and 9th of Fourth Month.
The forepart was much descriptive of my own situation for a long course of time;
and at times I did not expect ever to experience favour to be renewed.
I am through mercy somewhat relieved from the weight
of distress I had endured many months,
and labouring to stand single and resigned.
It is acceptable to find light and favour is renewed to you;
and perhaps you are now enabled to see that the trying dispensations
which attended you were for the great work of sanctification,
and that you might speak from living,
feeling experience of what the Lord has done for your soul.
You know the Lord`'s people formerly had many trials, conflicts and engagements,
before the old inhabitants were removed; and yet some were allowed to remain,
to prove their faith and patience; and it requires great watchfulness,
circumspection and humility, with daily dependence, to keep inward quiet and peace.
But the Lamb and his followers will have the victory.

I hear a good account of you, and wish your steady attention and faithfulness to the gift.
You must expect while here to meet with conflicts, provings of faith and patience;
we are given to expect it.
"`In the world you shall have tribulation, but in me peace.`"
May you be strengthened to abide in his love,
so will you experience the joy of the Lord to be your strength.
And let it be your care,
whatever you may meet with which may be hard to the natural part,
to sink down into patience, with a hope that all things shall work together for good.
I did hope and am rejoiced to find your beloved wife comes forward,
and trust she will become a helpmeet to you,
and that you will become one another`'s joy in the Lord.
I had sympathy with her when present,
as I thought I saw and felt there was a strong conflict
between the house of Saul and the house of David,
and I am glad to find the latter waxes stronger and stronger.
My dear love to her and your lovely children;
and revive in her remembrance that the righteous shall hold on their way.
May she be strengthened to become victorious.
// lint-disable invalid-characters
I am glad to find my countryman, Jacob Duché,
was so sustained under the great trial he experienced.
The value of religion is best known under great trials; there is something to recur to,
that stays and steadies the mind.
My love to him and wife.
I wish him to see through all mixtures,
and to become truly simple and open to the instruction of the still small voice.
This will settle his mind and gain him more true
wisdom and instruction than volumes of books,
and dipping into mysterious writings, that may and does tend more to perplex than edify.
It will be acceptable to hear from you, etc.,

[.signed-section-closing]
Your loving friend,

[.signed-section-signature]
John Pemberton

--

// lint-disable invalid-characters
When John Pemberton was in England, I showed him the way to Jacob Duché`'s house.
He was a minister of the church of England, and a very pious man;
but I apprehend he had somewhat confused himself by reading the writings of Swedenborg,
Boehmen, and other mysterious writers;
and when we called on him I believe his mind was in a great deal of perplexity.
We had some serious conversation with him, and left him in an agreeable state of mind.
In a few months afterward he called on me,
and seemed to wish for a continuance of acquaintance.
After a time he gave up to what he believed a religious duty,
by relinquishing his church preferments, which were valuable, and withdrew into privacy.
The reason he gave me for taking this step was,
that he did not believe it was right to receive money for preaching,
but considered that the Gospel should be dispensed freely,
and uncontaminated with the love of gain.
At first he had no objection to preach a funeral or charity sermon.
He had a wife, son, and two daughters, all religiously inclined.
The son was an artist, and had travelled a great deal on the continent of Europe,
in order to improve himself in the art of painting, in which he excelled.
He had studied under Benjamin West.
He undertook to paint the history of our Saviour,
and finished some of his pieces in a superior style.
He used frequently to converse with me on the subject of painting,
as regarded in a religious point of view.
On this, I freely gave him my opinion, namely,
that I would not take upon me to say that painting or drawing was sinful in itself;
but I thought it might, if indulged in, become a passion,
and really be the "`sin that easily besets;`" that when
we are convinced in our minds that this is the case,
as regards any pursuit,
and we so far indulge in it as that it has the preeminence in our thoughts,
it then partakes of the nature of idolatry, against which we should be ever on our guard.
I had a great affection for this young man, and I believe it was reciprocal.
Though he was athletic, and well grown as to outward appearance,
yet he had symptoms of pulmonary disease, that led me to fear he was not long lived.
A blood-vessel had broken internally;
and I observed whenever he was earnest in pursuing his favourite object, painting,
that the vessel discharged blood for several days together; and if he kept quiet,
the bleeding stopped and his health appeared restored.
I urged his giving up the employment, but he excused himself from so doing,
by saying that his necessities now obliged him to pursue it.
He however got worse and took to his bed, and was often in a heavenly frame of mind.

On my speaking to him respecting the awfulness of his situation,
he remarked to his father that he had, during his illness,
recollected what I had said to him on the subject of painting,
and that now he had an indubitable evidence that
I was right in the observations I had made,
and if it would please the Lord to restore him,
he never would renew that employment again,
believing it was an employment that was sinful to him.
I was much with him during his illness: towards the close of it,
one or other of his friends sat up with him at night.
One night I went to the house intending to sit up with him.
When I knocked at the door, his father opened it, and on my asking him how his son did,
with a sweet smile he answered, "`He is well, he is happy, and I am happy.
He died about half an hour since, and departed most gloriously.
We were all around him when he said, '`I see the holy angels waiting for me,
to convey my spirit into the bosom of my Saviour.
Don`'t you see them?
there they are all round the bed.`'
In this situation he died;
triumphantly singing the praises of Him whom his soul was anxiously waiting to behold.`"
It was this occurrence that John Pemberton referred to in his letter.
// lint-disable invalid-characters
I may here mention a circumstance respecting Jacob Duché,
that at the time appeared interesting.

He called on me one day early in the week,
to consult me as he said on a subject of some importance;
and proceeded to inform me that the Bishop of London had ordered
him to preach in St. Paul`'s Church on the next Sunday,
and that having given up his preferments he felt a difficulty about it.--I told
him it was a matter that it would be improper for me to interfere about;
he certainly should be the best judge of his own feelings: I added,
I thought he had got so far on his religious journey as to call no man master;
at the same time I wished him to pursue that which would be most easy to his
own mind.-- He told me that in looking at it in the best manner he was able,
and seeking best instruction,
he thought he should be most satisfied to go.--I
told him I did not feel at all uneasy about it,
and I earnestly wished him well through the business.
In the course of the conversation, he said in rather a peevish way,
that he knew I apprehended it was not the best way to write a sermon beforehand;
but he had considered the subject,
and he thought if he sat down on the Saturday and
depended on Divine assistance for its composition,
it must be equally acceptable as though he had waited till the Sunday
to receive instruction in the pulpit in order to deliver an extempore
discourse.--I replied that in the days of our ignorance and weakness,
these things might be winked at; but when the dispensation came,
in which we had an unshaken belief that we must live by faith,
it was then I apprehended very different; but I did not wish to dictate to him;
my solicitude for him was, that he might be directed right.--We then parted.

The beginning of the next week he called on me again,
when he appeared as though a great load had been taken from him,
so innocently cheerful that I could not but remark it to him.
He told me it really was the case,
that he felt his mind covered with love and peace on account
of having faithfully fulfilled his commision at St. Paul`'s;
that his mind had been greatly exercised previous to the day he went;
and when he got there one clergyman read the prayers, another read the communion service,
and while the Psalms were singing he got into the
pulpit and laid his sermon on the cushion.
During this time he felt great agitation of mind, though he knew not the reason.
Previous to his preaching, he knelt down as is usual,
and fervently prayed for Divine assistance,
and that what he should have to deliver might be effectual to the hearts of his hearers, etc.
He believed he prayed from his heart;
but O the exercise he was under when he opened his sermon!
He felt an injunction as clear as if he had been verbally told it,
that he must not preach that sermon.
What was he to do?
There was not a moment to lose;
the congregation were all in expectation and looking at him.
A part of the epistle for the day, as in an instant, came into his mind,
from which he took his text; and he proceeded in the faith that the Lord would help him,
and he was not deceived.
Matter seemed to flow in so extraordinary a manner, that he was humbled as in the dust.
Feeling deeply the subject he was upon, the tears flowed down his cheeks,
as well as down the cheeks of his audience.
There was no lack of words, no halting,
the only difficulty now was to know when he should come to a period,
so much fresh matter seemed to press upon him.
He however stopped in good time, under the covering of Divine favour.
When he came out of the pulpit he was surrounded by the congregation,
who expressed their grateful thanks for the blessing they had received through his sermon.
"`And thankful was I,`" said he, "`when I got home;
nor did I omit to return thanks where it was due,
for the condescending favour I had received: but`" he added,
"`it was you that brought me into the difficulty,
although I have reason to bless God for the termination of it.`"

Very soon after I was received as a member of the Society of Friends,
and had the privilege of sitting in their meetings for discipline,
I thought I discerned the great advantage of private labour;
of endeavouring with all privacy, if possible,
to restore any individual that may have been overtaken with a fault;
thus watching over one another for good in true love.
I had opportunities very early of observing the benefit that resulted from such labour;
and although sometimes it has been difficult at first to make a due impression,
yet in most instances, when Divine aid was sought,
the humble endeavour has been crowned with success.

An instance in point occurred about this time:-A young man
who had from early youth shown very many bad dispositions,
and great depravity of mind, had, at times, engaged a good deal of my attention.
He had an amiable mother to whom he behaved very unkindly.
I frequently remonstrated with him on his unbecoming conduct,
but without any seeming good effect.
He indulged in loose company, in reading improper books,
in attending the theatre and other dissipations;
and gave liberty to his passions till he became hardened,
and seemed to have lost every trace of anything like tenderness of disposition.
While in his career of folly, his father, who had been very tender over him, died;
and his mother had been seized with a paralytic affection,
so that her faculties and all her powers were much impaired.

After the funeral, a Friend and myself called on this young man,
and had a serious opportunity with him,
wherein his state was spoken to in a remarkable manner.
He was urged particularly to look at his awful situation,
and told if he possessed any feeling at that moment,
he could not but be sensible that the hand of Omnipotence was upon him,
in order to show him that all power belongs to Him,
and that it is in vain for us to struggle against it.
It was also added,
that although he might apprehend he could not be under a
more heavy or trying dispensation than the present,
yet he must not be surprised if a greater trial was at hand,
in order that he might be instructed more deeply than he ever yet had been,
in the necessity of obedience to the Divine command.
He was much offended at this plain dealing, and he mentioned as much to a Friend; adding,
that he had a great mind to have left the room,
for he was sure no greater trial could befall him than the present.
In less than two weeks from this time, to my surprise,
he sent to me to let me know he was dangerously ill,
and to request that I would call upon him as soon as I could.

As soon as I saw him, he made a humble apology for sending for me,
and said he had so far come to his senses as to see that I had, for a length of time,
been his true friend, and one in whom he could confide;
though he had foolishly resisted every attempt I
had made to persuade him to more consistent conduct.
I told him he never had offended me; for all that I had ever done in that respect,
had been with a view towards his real happiness;
that I was rejoiced to find him in such an agreeable disposition;
and that he might depend on a continuation of my friendly regard to him.
On inquiry as to the state of his health, I found he had a violent fever;
and from the irritability of his nervous system,
there was great reason to suspect that in a few hours he would become delirious,
in which case it would be very uncertain how the complaint would terminate.
I therefore recommended that a physician should be sent for immediately;
and that he should settle his affairs and make his will without delay,
and in as concise a way as he could.
All this was done previous to the coming on of the delirium.
In the mean time he earnestly requested I would not leave him more than I could help;
I therefore stayed with him as much as I could in the day time,
and took my turn to sit up with him at night,
I lost no opportunity of endeavouring to turn his attention to
the important matter of his soul`'s salvation through Jesus Christ.
The delirium did not last so long as was at first expected;
but the fever continued several weeks.
I knew he had imbibed deistical notions,
which I had feared would make it difficult by the
mere force of reason to convince him of his errors:
my dependence was on our divine Helper, who was pleased to bless the work.

One day I ventured to ask him if he had any objection
to see a minister who was then in London;
to which he objected, on account,
(as he said) of his always preaching from Solomon`'s Song.
However a few days afterward,
when we were discoursing on the necessity of faith in Jesus Christ,
he broke out into a sort of ecstasy as follows: "`Tell me, you whom my soul loves,
where you feed your flock, and where you rest at noon-day;
for why should I be as one that turns aside.`"
This he spoke with great earnestness, and burst into a flood of tears,
more especially after repeating the latter part of the sentence.
During some part of his illness he was all agitation and fears,
lest he should die and be utterly miserable.
One night in particular, he said he wished to go to sleep, but could not,
unless I would let him take hold of my hand: he awoke several times in great horror,
crying out, O save me! save me! saying, when he was a little awake,
"`O do not leave me Frederick!
I thought I was just dropping into the flames that appeared underneath me;
don`'t let go my hand.`"
After a time he became more composed, and he wished me to read some of Cowper`'s Hymns.
I selected one, entitled The Contrite Heart, and having read it,
he was much pleased with it; said he should like to learn it,
and if I would read it again, he would repeat after me.
The first stanza seemed to affect him much.

[verse]
____
The Lord will happiness divine
On contrite hearts bestow;
Then tell me gracious God, is mine
A contrite heart or no.
____

When he came to the two last lines, he burst into tears;
and with a degree of earnestness he cried out,

[verse]
____
Then tell me gracious God,
is mine a contrite heart or no.
____

and this he did every time he repeated these lines.
It was a great relief to my mind to observe the gradual
unfoldings of Divine goodness to this young man:
it was by the power of Divine grace alone,
that he was made to see the excellency of the Christian dispensation.
One day, while conversing on the sufferings and death of Christ,
he seemed to enter into the nature of his suffering on the cross,
and spoke of it with that sensible feeling,
which none but those who are favoured to experience its efficacy could manifest.
"`O,`" said he, "`the goodness of God to institute such a plan of redemption for poor,
lost man.
And did he suffer all these things for me!
Ah what must have been the sufferings of the holy Jesus,
in bearing the sins of the whole world, when I am so unable to bear my own?
Did he die for me, a wretched sinner O, the goodness of God!`"

These, and many more expressions, from true religious feeling he uttered,
the tears trickling down his cheeks.
He was brought to such a state as to believe, if he was favoured to die then,
he should be received into glory, and seemed devoutly to wait for his change.
But his disorder abated; and when he perceived he was likely to recover,
he felt keen distress; and said that his multiplied weaknesses,
and his natural inclination to evil, which none knew but himself,
caused in him such a dread of again entering into the world, as he could not express.
It pleased Him who orders all things well, gradually to restore him to health.

The Almighty, in his dispensations towards the children of men,
acts as seems good to himself;
and it not unfrequently happens that the ways of
his Providence are involved in deep mystery,
which in his own time he is often pleased to reveal.
Conceived in sin, man dwells in the midst of darkness,
which can only be dispelled by the influence of Divine grace.
With some, as with the Apostle Paul, the mind is at once so divinely illuminated,
that they pass forthwith out of the gloomy darkness of death
into the marvellous light of the kingdom of God;
with others the change is less rapid,
the shades of ignorance gradually dispersing and vanishing,
as the night yields to the approach of the morning light.
In the following narrative, we discover the power and excellence of Divine goodness,
and a great display of heavenly condescension.--

About the year 1797, I became acquainted with Count N+++_______+++, a native of Ireland.
In early youth he was sent by his parents into Germany,
and was educated at one of the Universities there.
He was brought up in the Roman Catholic persuasion; the inconsistency of which,
he told me, he very early saw.
The bigotry, superstition,
and wickedness of the priests were such as to give him a disgust to religion; believing,
he said, that the foundation of it was dissimulation and priestcraft.
When he left the University, he was introduced to the Emperor, Joseph the Second,
to whom he afterwards became Lord of the Bedchamber,
and was soon made an officer of rank in the German army,
a part of which he commanded in a war against the Turks.
The Emperor made him a Count,
in addition to his hereditary titles of Marquis and Wiscount of Waledesto, in Spain;
and he was also a grandee of the first rank in that kingdom.
He was besides related to some of the first nobility in England and Ireland.

At the commencement of our acquaintance,
he expressed a wish to know something of the principles of Friends.
I lent him Barclay`'s Apology, which he read: when he returned it,
he told me it was the best written book on divinity he had ever seen;
and if it were possible to act according to the sentiments contained in it,
no man could act wrong: but he added, "`I have something to say to you in private,
which I hardly dare say to any man.
Unfortunately for me, I do not believe in any system of religion;
I do not even believe in the existence of God.
You may be assured it is a subject which has given me a great deal of thought;
and when I came into this Protestant country,
I had hoped I should have discovered the essence of truth,
and that the Protestant clergy would have given the lie
to the impressions I had imbibed from my early prejudices,
on account of the dissolute and abandoned lives of the Romish clergy.
But alas!
I perceive there is the same system of deception carried on in England as in Germany.
The clergy have only one thing in view, and that is the accumulation of wealth; and,
where it can be done, to endeavour after splendour and aggrandizement.
As to their flocks, it is a matter of no consequence whether they are ignorant or wise;
it appears no part of their study to aim at their religious improvement;
so that I find myself just where I was.
I observe that all mankind are alike; they pretend to religion, and that is all;
they talk of it and there they leave it.
As a confirmation of what I say, I may inform you,
that on my first coming into these parts, I paid a visit to my relations in Ireland,
who showed me great hospitality and kindness; and, as is usual in that country,
there were large convivial parties,
where neither the manners nor the conversation would bear much reflection,
even in an infidel (as I suppose I should be called.)

"`It happened that the conversation one evening took a religious turn,
in the course of which I inadvertently leaned towards scepticism.
On this, one of the company hastily said, '`Surely sir,
you don`'t doubt the existence of a Supreme Being;`'--to which I replied,
'`What are your sentiments on that subject?`' Why sir, my sentiments are these:
I look upon the Almighty as of infinite purity, as the object both of love and fear;
that I am in his immediate presence; it is through him I live and move and have my being.
I consider that I am amenable to him for every action of my life;
that if I do evil voluntarily, I run the hazard of his eternal displeasure,
but if I act according to his will, I shall be eternally happy.`'--'`Is this, sir,
really and truly your belief?`"--"`Yes sir, it undoubtedly is;
and it is also the belief of every well-regulated Christian.`"--"`Then sir,
how comes it to pass that your actions correspond so little with your professions!
Is it possible that such a hearsay evidence as this would convince me, were I an atheist,
of the truth of God`'s existence?
Has any part of your conduct, since we have been so often together,
manifested either love, or fear, or reverence for this object of your pretended regard;
I wish not to give you offence,
but see whether there is anything like consistency between your declarations
and the conduct I am led to fear you are in the habitual practice of.`"
The gentleman seemed confused and thoughtful;
and I immediately turned the discourse to another subject.`"

I was much struck with this conversation, and considerably more so,
when he told me that he had left Germany on account
of his objection to serve any longer in the army.
The thought of taking away the life of a fellow-man,
had become distressing and perplexing to him; so much so,
that he at length resolved he would in no way be accessory to it.
He added, that since he had been in England, a relation of his, the Marquis of B+++_______+++,
had kindly offered to raise a regiment of horse in Ireland,
and get him the command of it, which he had politely refused,
on the ground mentioned above;
and that this had been the occasion of the Marquis`'s displeasure,
and the loss of his friendship.
From what I could gather, the Marquis had shown him much attention,
and had conferred on him many favours;
but the natural impetuosity of Count N+++_______+++`'s temper,
and the hauteur he had acquired in the German court,
had rendered him impatient of contradiction;
so that I had reason to suspect the Marquis had taken
umbrage at some other part of his conduct,
in addition to his refusal of the generous offer of preferment in Ireland.

I felt much interested for this person,
and carefully concealed from every one what his sentiments were.
I apprehended that where there appeared so great sincerity,
the Almighty would reveal himself in his own time.
He seemed much gratified by attending our religious meetings,
and I have many times seen him much affected and in tears.
He used frequently, in a modest way, to argue with me the point of his disbelief;
but never, I believe to much purpose on his part.
I lent him several books wherein the existence of God was treated of;
but all seemed unavailing.
He made notes on a Bible I lent him, almost through the whole book,
in opposition to its precepts and doctrines.
Towards the close of his infidelity, he requested I would lend him Newton`'s [.book-title]#Principia#;
which I refused, in the belief, as I told him, that he had wandered far in the dark,
by seeking for that without, which was only to be discovered in the secret of the heart;
I therefore advised him to keep his mind quiet, adding,
that I believed the Almighty would one day make himself known to him,
but he must not be surprised if He should do it in such a way, as would, in his view,
be contemptible.

A few weeks after this, two female Friends, Ann Christy and Deborah Moline,
had a concern to visit the families of Westminster meeting,
as also those who were attenders but not in membership.
As Count N+++_______+++ had for a considerable time been an almost constant attender,
his name was set down with two others;
and I requested the Friends to let me sit with them.
Very soon after we were seated,
Divine Goodness was pleased to overshadow this little assembly.
The poor object of this narrative, in a few minutes burst into tears,
and continued in this humbled state for nearly twenty minutes before a word was uttered;
when one of the females, unlearned as to human attainments,
but who had waited for Christ to be her Instructor, expressed herself to this effect:
That she had felt an extraordinary solemnity at our first sitting down,
which had continued to the present time; so much so, that she had feared to speak,
although she also feared to keep silence,
more especially as the subject which had come before her,
was of a truly awful and extraordinary nature.
"`Surely,`" she said, "`there is no person present,
who has any doubts respecting the existence of a Supreme Being.
If there is, I would have such to look into their own hearts,
and observe the secret operation of something they cannot but feel.
When they have committed an evil action, how does it torment the poor mind,
and render it for a time continually uneasy?
On the other hand, when they have acted well and have avoided the temptation to evil,
what a sweet glow of approbation has covered the mind.
From which proceed this uneasiness and this approbation?
Man cannot communicate such sensations to himself.
Be assured they come from God; no,
it is God himself who thus speaks in the inmost of the soul.`"
The Friend said but little more--to the person addressed it was
a volume--it was as though the windows of heaven were opened--to
myself it was an opportunity never to be forgotten.

About two days afterwards, my friend called on me in the evening,
and requested to have some conversation with me, to which I readily agreed.
Without much preface, he told me,
that he knew not how he could be sufficiently grateful for the patience I had shown him,
or for the kind concern I had manifested for his welfare; but he added,
"`I believe it will give you inconceivable pleasure,
to be informed that I have not a doubt remaining.
I am full of thankfulness to that Almighty Being,
who in mercy has made himself known to this poor benighted heart of mine,
in some degree through the instrumentality of that dear woman;
though I may acknowledge to you, that before a word was spoken,
the business was completed.
I had taken great pains, as you know, to invalidate the Scripture testimonies;
but at that solemn and heavenly opportunity,
all the arguments I had made use of for this purpose, reverted back,
and I became ashamed and confounded.
I felt as it were, all at once, the certain evidence of a merciful and kind God,
which so overcame me, that I could only show my love and gratitude by my tears;
so that for a while, I appeared as in heaven, that is,
in a state of mind far beyond what any earthly object could bestow.
The dear woman was doubtless sensible of my situation,
she having confirmed to me the evidence I felt in my own soul.
I thought this evening, that though I had been thus favoured,
it would be difficult to prove the divinity of Christ,
a doctrine which I had conceived to be altogether absurd; but on coming up your steps,
and waiting to speak to you, the whole mystery was unfolded,
and I now have no doubts on that subject.`"
He explained to me his views on this point, in a remarkable manner;
as also on the creation of man, his fall, and other serious subjects,
so as to leave me no doubt that he had been favoured with a Divine illumination.
His very nature seemed altered, and his countenance changed.
From the haughtiness so often observable in those who possess outward rank in society,
he was now become mild and passive like a little child.

I remember, soon after this occurrence, his calling on me one morning, when,
during the previous night, there had been a dreadful storm,
attended with violent thunder and lightning.
He related his feelings at the time, which were very striking.
He said that previous to this storm he had never known what the fear of death was;
for he had supposed death to be mere annihilation,
when both soul and body were destroyed at the same moment.
But now the case was different; he saw his awful situation,
that in an instant he might be in the presence of that Being
whom he had contemned during his whole life.
His sins were ranged in order before him,
and he felt all the horrors of self-condemnation and fear.
In this situation he was led to pray fervently for forgiveness for the past,
and preservation for the future.
It was a new scene in the period of his existence,
the effect of which words could not express.
After his mind had been thus graciously visited and enlightened,
his naturally imperious temper would frequently show itself in sudden fits of passion,
for which he often expressed his sorrow.
Perhaps this natural temper was permitted to assail him
in order to convince him of the necessity of watchfulness,
and of guarding against dependence on his own strength.
It is but justice to him to say,
that he never showed intemperate behaviour towards myself,
but always treated me with the greatest respect.

He had a sister, a Roman Catholic, married to a nobleman at Strasburg,
with whom he intended to reside.
The necessity for this he very often lamented,
because he would in that case be surrounded by the Romish clergy,
whom he despised as gross hypocrites, but towards whom he must behave with civility,
which would be a great task to him.
Previously to his leaving England,
he requested to be supplied with some of the writings of Friends,
feeling more satisfaction in the perusal of them than any other books.
He attended Friends`' meetings regularly till his departure.

[.small-break]
'''

+++[+++This last narrative concludes the Memoirs of Frederick Smith, as written by himself.
About the year 1806, he removed from the Haymarket, Westminster, to Croydon,
where he continued to reside till his decease.--The following brief sketch of his character,
and account of his last illness and death,
are extracted from the Testimony of Kingston Monthly Meeting.]

[.embedded-content-document.testimony]
--

He did not travel much in the work of the ministry, although it appears,
that from the year 1790 to 1818, with the approbation of his friends,
he performed journeys in that service through various counties in England,
and was often engaged in visits to the families of Friends:
and having deeply partaken of the sufferings,
as well as of the consolations of the Gospel, he was, in his ministry and otherwise,
a true sympathizer with the afflicted and mournful,
pouring in the wine and oil for their refreshment and comfort.
A large portion of his time was occupied in endeavouring
to alleviate the distresses of his fellow creatures;
he was actively engaged in promoting many public institutions for benevolent purposes;
he also devoted himself for the good of others in a more private capacity,
and was frequently engaged as a peace-maker in healing of differences.
He was not only exemplary himself,
but also zealous in encouraging others in the diligent attendance of our religious meetings.
His conversation was innocently cheerful,
and his affectionate disposition procured for him great influence over the youth:
+++[+++the two Addresses which follow these Memoirs,
show how deeply he was concerned that this interesting class of his fellow-professors,
should be found walking in the truth.]

He had, for a considerable time been liable to an affection of the heart,
but did not appear to grow materially worse until the 20th of Fourth Month, 1823; when,
after a restless night, in the morning he was seized with a violent paroxysm;
this continued about three-quarters of an hour, and was succeeded by violent retchings,
at intervals, until noon the next day: from that time he appeared quite easy.
On coming to himself, he said, "`I believe my time will not now be long; God bless you,
God Almighty bless you.
I only desire resignation, and I feel resignation,
and am willing to suffer whatever the Lord may think fit to inflict upon me.`"
He then prayed fervently and with great energy,
"`Let not your hand spare nor your eye pity,
till you have made me what you would have me to be:`" and said,
"`this has been my constant prayer for several weeks, I may say months past:
my sufferings have been very great for some hours, but I can bear all, everything,
ah yes, no matter what, if it be His will.
Almighty God bless you all, and all my dear friends.
O Lord God, your hand is upon me! enable me to bear all to the end.
I feel resigned either to stay or go; the Lord`'s will be done.
The Lord is good, he is very good; he has given me a kind and affectionate wife,
dutiful and affectionate children;`" and he enumerated
other blessings that excited his feelings of gratitude.
After this, his breathing being very oppressive,
it was with difficulty he could express himself; but his uniform reply to inquiries was,
"`I feel very comfortable.`"
He lay in a peaceful, quiet state, and was sensible to the last.
About two minutes before his departure, he asked one of his children to take his hand,
and without sigh or groan expired.

He died the 22nd of Fourth Month, 1823, at Croydon,
and was interred there on the 27th of the same,
previous to a very large and solemn meeting; aged sixty-six,
a minister about thirty-four years.

--
